# -*- coding: utf-8 -*-
"""Page-content translations, keyed by the exact English string in the template.

Templates call these through the `|t` Jinja filter: `{{ 'Road Status'|t }}`.
English is the source language, so there is no 'en' dict — a lookup for 'en'
returns the key itself.

ponytail: Newari and Maithili fall back to Nepali for page content (see
FALLBACK). The short UI keys in translation_service.py are properly translated
into all four; hand-translating 350 page strings into Newari and Maithili needs
a speaker of each, and inventing them would be worse than falling back.
"""

FALLBACK = {'newari': 'ne', 'maithili': 'ne'}

NE = {
    # --- auth ---
    'Authority Login': 'निकाय लगइन',
    'Government & Organization Access': 'सरकारी तथा संस्थागत पहुँच',
    'Username': 'प्रयोगकर्ता नाम',
    'Password': 'पासवर्ड',
    'Remember me': 'मलाई सम्झनुहोस्',
    'Login to Authority Panel': 'निकाय प्यानलमा लगइन गर्नुहोस्',
    'Register as Authority': 'निकायको रूपमा दर्ता गर्नुहोस्',
    'Citizen Login': 'नागरिक लगइन',
    'Enter authority username': 'निकायको प्रयोगकर्ता नाम लेख्नुहोस्',
    'Enter password': 'पासवर्ड लेख्नुहोस्',
    'Authority Registration': 'निकाय दर्ता',
    'Register your government organization': 'आफ्नो सरकारी संस्था दर्ता गर्नुहोस्',
    'Organization Name': 'संस्थाको नाम',
    'Organization email': 'संस्थाको इमेल',
    'Choose username': 'प्रयोगकर्ता नाम छान्नुहोस्',
    'Create password': 'पासवर्ड बनाउनुहोस्',
    'Register Authority Account': 'निकाय खाता दर्ता गर्नुहोस्',
    'Citizen Registration': 'नागरिक दर्ता',
    'e.g., Sindhuli Road Division Office': 'जस्तै, सिन्धुली सडक डिभिजन कार्यालय',
    'Welcome Back': 'पुनः स्वागत छ',
    'Login to continue to your dashboard': 'आफ्नो ड्यासबोर्डमा जान लगइन गर्नुहोस्',
    'Login': 'लगइन',
    "Don't have an account?": 'खाता छैन?',
    'Register here': 'यहाँ दर्ता गर्नुहोस्',
    'Enter your username': 'आफ्नो प्रयोगकर्ता नाम लेख्नुहोस्',
    'Enter your password': 'आफ्नो पासवर्ड लेख्नुहोस्',
    'Create Account': 'खाता खोल्नुहोस्',
    'Join your district on NepalSathi': 'नेपालसाथीमा आफ्नो जिल्लासँग जोडिनुहोस्',
    'Register': 'दर्ता',
    'Already have an account?': 'पहिले नै खाता छ?',
    'Login here': 'यहाँ लगइन गर्नुहोस्',
    'Choose a username': 'प्रयोगकर्ता नाम छान्नुहोस्',
    'Enter your email': 'आफ्नो इमेल लेख्नुहोस्',
    'Create a password': 'पासवर्ड बनाउनुहोस्',

    # --- shared labels ---
    'Category': 'श्रेणी',
    'District': 'जिल्ला',
    'Phone': 'फोन',
    'Email': 'इमेल',
    'Status': 'अवस्था',
    'Description': 'विवरण',
    'Location': 'स्थान',
    'Authority': 'निकाय',
    'Authorities': 'निकायहरू',
    'Province': 'प्रदेश',
    'Districts': 'जिल्लाहरू',
    'Dashboard': 'ड्यासबोर्ड',
    'Projects': 'आयोजनाहरू',
    'Roads': 'सडकहरू',
    'Rivers': 'नदीहरू',
    'Posts': 'पोस्टहरू',
    'Complaints': 'उजुरीहरू',
    'Logout': 'लगआउट',
    'Filter': 'फिल्टर',
    'All Districts': 'सबै जिल्लाहरू',
    'Filter by District:': 'जिल्ला अनुसार छान्नुहोस्:',
    'View All': 'सबै हेर्नुहोस्',
    'View Details': 'विवरण हेर्नुहोस्',
    'Category:': 'श्रेणी:',
    'Urgency:': 'अत्यावश्यकता:',
    'Location:': 'स्थान:',
    'Status:': 'अवस्था:',
    'Filed by:': 'दर्ता गर्ने:',
    'Filed on:': 'दर्ता मिति:',
    'Filed:': 'दर्ता:',
    'Last Updated:': 'अन्तिम अद्यावधिक:',
    'Description:': 'विवरण:',
    'Progress:': 'प्रगति:',
    'Phone:': 'फोन:',
    'Email:': 'इमेल:',
    'Address:': 'ठेगाना:',
    'Hours:': 'समय:',
    'Ticket:': 'टिकट:',
    'Level:': 'सतह:',
    'Danger:': 'खतरा:',
    'Date:': 'मिति:',
    'Time:': 'समय:',
    'Route:': 'मार्ग:',
    'Distance:': 'दूरी:',
    'Budget:': 'बजेट:',
    'Spent:': 'खर्च:',
    'Contractor:': 'निर्माण कम्पनी:',
    'Start Date:': 'सुरु मिति:',
    'Expected Completion:': 'सम्भावित सम्पन्न मिति:',
    'Current Level:': 'हालको सतह:',
    'Danger Level:': 'खतरा सतह:',
    'Your District:': 'तपाईंको जिल्ला:',
    'Joined:': 'सामेल मिति:',
    'Headquarters:': 'सदरमुकाम:',
    'District ID:': 'जिल्ला आईडी:',
    'Authority ID:': 'निकाय आईडी:',
    'Response:': 'जवाफ:',
    'VERIFIED': 'प्रमाणित',
    'VERIFIED AUTHORITY': 'प्रमाणित निकाय',
    'CITIZEN': 'नागरिक',
    'km': 'कि.मि.',
    'complete': 'सम्पन्न',
    'posts': 'पोस्टहरू',
    'complaints': 'उजुरीहरू',
    'Not specified': 'उल्लेख गरिएको छैन',
    'N/A': 'उपलब्ध छैन',

    # --- categories and statuses (also rendered raw from the database) ---
    'Road Division': 'सडक डिभिजन',
    'Police': 'प्रहरी',
    'Electricity Authority': 'विद्युत प्राधिकरण',
    'Electricity': 'विद्युत',
    'Water Supply': 'खानेपानी',
    'Health Office': 'स्वास्थ्य कार्यालय',
    'Municipality': 'नगरपालिका',
    'Disaster Management': 'विपद् व्यवस्थापन',
    'Other': 'अन्य',
    'Road Blocked': 'सडक अवरुद्ध',
    'Waste Management': 'फोहोर व्यवस्थापन',
    'Landslide': 'पहिरो',
    'Bridge Damage': 'पुल क्षति',
    'Drainage': 'ढल',
    'Pending': 'विचाराधीन',
    'In Progress': 'कार्यरत',
    'Resolved': 'समाधान भयो',
    'Rejected': 'अस्वीकृत',
    'Normal': 'सामान्य',
    'Rising': 'बढ्दै',
    'High': 'उच्च',
    'Medium': 'मध्यम',
    'Low': 'कम',
    'Critical': 'अति जरुरी',
    'Flooding': 'बाढी',
    'Flood': 'बाढी',
    'Open': 'खुला',
    'Partially Open': 'आंशिक खुला',
    'Restricted': 'प्रतिबन्धित',
    'Blocked': 'अवरुद्ध',
    'Moderate': 'मध्यम',
    'Heavy': 'धेरै',
    'Severe': 'अति धेरै',
    'Traffic': 'ट्राफिक',
    'Road Condition': 'सडक अवस्था',
    'Weather': 'मौसम',
    'Development': 'विकास',
    'News': 'समाचार',
    'Emergency': 'आपतकालीन',
    'road': 'सडक',
    'police': 'प्रहरी',
    'electricity': 'विद्युत',
    'water': 'खानेपानी',
    'water_supply': 'खानेपानी',
    'health': 'स्वास्थ्य',
    'municipality': 'नगरपालिका',
    'disaster': 'विपद्',
    'other': 'अन्य',
    'open': 'खुला',
    'partial': 'आंशिक',
    'restricted': 'प्रतिबन्धित',
    'blocked': 'अवरुद्ध',
    'low': 'कम',
    'moderate': 'मध्यम',
    'heavy': 'धेरै',
    'severe': 'अति धेरै',
    'normal': 'सामान्य',
    'rising': 'बढ्दै',
    'high': 'उच्च',
    'medium': 'मध्यम',
    'critical': 'अति जरुरी',
    'flooding': 'बाढी',
    'flood': 'बाढी',
    'pending': 'विचाराधीन',
    'in_progress': 'कार्यरत',
    'resolved': 'समाधान भयो',
    'rejected': 'अस्वीकृत',
    'on_schedule': 'समयमै',
    'delayed': 'ढिलो',
    'completed': 'सम्पन्न',
    'road_blocked': 'सडक अवरुद्ध',
    'waste': 'फोहोर',
    'landslide': 'पहिरो',
    'bridge': 'पुल',
    'drainage': 'ढल',
    'traffic': 'ट्राफिक',
    'road_condition': 'सडक अवस्था',
    'weather': 'मौसम',
    'development': 'विकास',
    'emergency': 'आपतकालीन',
    'news': 'समाचार',
    'general': 'सामान्य',
    'announcement': 'घोषणा',
    'progress': 'प्रगति',

    # --- navigation and chrome ---
    'Select language': 'भाषा छान्नुहोस्',
    'Language': 'भाषा',
    'District Intelligence': 'जिल्ला जानकारी',
    'Overview': 'सिंहावलोकन',
    'Infrastructure': 'पूर्वाधार',
    'Community': 'समुदाय',
    'Civic': 'नागरिक',
    'Dark mode': 'डार्क मोड',
    'Switch to dark mode': 'डार्क मोडमा जानुहोस्',
    'Toggle navigation': 'मेनु खोल्नुहोस् वा बन्द गर्नुहोस्',
    'Main': 'मुख्य',
    'Account': 'खाता',

    # --- authority panel ---
    'Authority Panel': 'निकाय प्यानल',
    'Authority Dashboard': 'निकाय ड्यासबोर्ड',
    'Total Complaints': 'कुल उजुरीहरू',
    'Recent Complaints': 'हालका उजुरीहरू',
    'No complaints.': 'कुनै उजुरी छैन।',
    'No complaints filed.': 'कुनै उजुरी दर्ता भएको छैन।',
    'Manage Projects': 'आयोजना व्यवस्थापन',
    'No projects assigned.': 'कुनै आयोजना तोकिएको छैन।',
    'Manage your development projects': 'आफ्ना विकास आयोजनाहरू व्यवस्थापन गर्नुहोस्',
    'Update Progress (%)': 'प्रगति अद्यावधिक (%)',
    'Update Description': 'अद्यावधिक विवरण',
    'Update Project': 'आयोजना अद्यावधिक गर्नुहोस्',
    'Describe the update...': 'अद्यावधिकको विवरण लेख्नुहोस्...',
    'River Management': 'नदी व्यवस्थापन',
    'Update river levels and issue warnings': 'नदीको सतह अद्यावधिक गरी चेतावनी जारी गर्नुहोस्',
    'Water Level (m)': 'पानीको सतह (मि.)',
    'Update River': 'नदी अद्यावधिक गर्नुहोस्',
    'No rivers in your district.': 'तपाईंको जिल्लामा कुनै नदी छैन।',
    'Road Management': 'सडक व्यवस्थापन',
    'Update road status in your district': 'आफ्नो जिल्लाको सडक अवस्था अद्यावधिक गर्नुहोस्',
    'Traffic Level': 'ट्राफिक स्तर',
    'Update Road': 'सडक अद्यावधिक गर्नुहोस्',
    'No roads in your district.': 'तपाईंको जिल्लामा कुनै सडक छैन।',
    'Complaint Details': 'उजुरी विवरण',
    'Previous Responses': 'अघिल्ला जवाफहरू',
    'No responses yet.': 'अहिलेसम्म कुनै जवाफ छैन।',
    'Send Response': 'जवाफ पठाउनुहोस्',
    'Update Status': 'अवस्था अद्यावधिक गर्नुहोस्',
    'Response Message': 'जवाफ सन्देश',
    'Type your response...': 'आफ्नो जवाफ लेख्नुहोस्...',
    'Respond': 'जवाफ दिनुहोस्',
    'All complaints filed to': 'यहाँ दर्ता भएका सबै उजुरीहरू:',

    # --- ai assistant ---
    'NepalSathi AI Assistant': 'नेपालसाथी एआई सहायक',
    'Ask questions about roads, rivers, projects, and travel in Nepal': 'नेपालका सडक, नदी, आयोजना र यात्राबारे प्रश्न सोध्नुहोस्',
    'Checking AI status...': 'एआई अवस्था जाँच गर्दै...',
    'I can help you with:': 'म तपाईंलाई यसमा सहयोग गर्न सक्छु:',
    'Road conditions in Nepal': 'नेपालको सडक अवस्था',
    'River levels and flood warnings': 'नदीको सतह र बाढी चेतावनी',
    'Development projects': 'विकास आयोजनाहरू',
    'Travel planning': 'यात्रा योजना',
    'Authority information': 'निकायसम्बन्धी जानकारी',
    'Emergency numbers': 'आपतकालीन नम्बरहरू',
    'Flood Warnings': 'बाढी चेतावनी',
    'Travel Advice': 'यात्रा सल्लाह',
    'File Complaint': 'उजुरी दर्ता',
    'Send': 'पठाउनुहोस्',
    'Type your question about Nepal...': 'नेपालबारे आफ्नो प्रश्न लेख्नुहोस्...',
    'Powered by Local AI (Ollama) • Qwen 2.5': 'स्थानीय एआई (Ollama) • Qwen 2.5 द्वारा सञ्चालित',

    # --- authority directory ---
    'Authority Directory': 'निकाय निर्देशिका',
    'Government authorities in your district': 'तपाईंको जिल्लाका सरकारी निकायहरू',

    # --- password and profile ---
    'Change Password': 'पासवर्ड परिवर्तन',
    'Current Password': 'हालको पासवर्ड',
    'New Password': 'नयाँ पासवर्ड',
    'Confirm New Password': 'नयाँ पासवर्ड पुष्टि गर्नुहोस्',
    'Back to Edit Profile': 'प्रोफाइल सम्पादनमा फर्कनुहोस्',
    'Edit Profile': 'प्रोफाइल सम्पादन',
    'Update your profile information': 'आफ्नो प्रोफाइल जानकारी अद्यावधिक गर्नुहोस्',
    'Phone (optional)': 'फोन (वैकल्पिक)',
    'Select District': 'जिल्ला छान्नुहोस्',
    'Bio (optional)': 'परिचय (वैकल्पिक)',
    'Save Changes': 'परिवर्तन सुरक्षित गर्नुहोस्',
    'Tell us about yourself...': 'आफ्नोबारे लेख्नुहोस्...',
    'Go to Authority Dashboard': 'निकाय ड्यासबोर्डमा जानुहोस्',
    'Reputation': 'प्रतिष्ठा',
    'Showing 10 of': 'देखाइएको: १० मध्ये',
    'Showing 5 of': 'देखाइएको: ५ मध्ये',
    'Create your first post': 'आफ्नो पहिलो पोस्ट सिर्जना गर्नुहोस्',
    'File a complaint': 'उजुरी दर्ता गर्नुहोस्',

    # --- complaints (citizen) ---
    'Government Response': 'सरकारी जवाफ',
    'Resolution Details': 'समाधान विवरण',
    'Back to My Complaints': 'मेरा उजुरीहरूमा फर्कनुहोस्',
    'My Complaints': 'मेरा उजुरीहरू',
    'Track your filed complaints': 'आफूले दर्ता गरेका उजुरीहरू ट्र्याक गर्नुहोस्',
    'No complaints filed yet.': 'अहिलेसम्म कुनै उजुरी दर्ता भएको छैन।',
    'File Your First Complaint': 'आफ्नो पहिलो उजुरी दर्ता गर्नुहोस्',
    'File a Complaint': 'उजुरी दर्ता गर्नुहोस्',
    'Report issues to the right authority': 'सही निकायमा समस्या जाहेर गर्नुहोस्',
    'Urgency': 'अत्यावश्यकता',
    'Submit Complaint': 'उजुरी पेश गर्नुहोस्',
    'Describe the issue...': 'समस्याको विवरण लेख्नुहोस्...',
    'e.g., Kamalamai, Sindhuli': 'जस्तै, कमलामाई, सिन्धुली',
    'Complaint': 'उजुरी',

    # --- posts and feed ---
    'Create Post': 'पोस्ट सिर्जना',
    '+ Create Post': '+ पोस्ट सिर्जना',
    'Share information with your community. AI will auto-classify your post.': 'आफ्नो समुदायसँग जानकारी साझा गर्नुहोस्। एआईले तपाईंको पोस्ट स्वतः वर्गीकरण गर्नेछ।',
    'Location (optional)': 'स्थान (वैकल्पिक)',
    'Content': 'सामग्री',
    'Add Photo (optional)': 'फोटो थप्नुहोस् (वैकल्पिक)',
    'Supported: PNG, JPG, JPEG, GIF, WEBP (Max 16MB)': 'समर्थित: PNG, JPG, JPEG, GIF, WEBP (अधिकतम 16MB)',
    'AI Will Classify This As:': 'एआईले यसलाई यसरी वर्गीकरण गर्नेछ:',
    'Post': 'पोस्ट',
    "What's happening? (Nepali or English)": 'के भइरहेको छ? (नेपाली वा अंग्रेजी)',
    'Preview': 'पूर्वावलोकन',
    'Community Feed': 'सामुदायिक फिड',
    'Latest updates from your community': 'तपाईंको समुदायका पछिल्ला अपडेटहरू',
    'Posts tagged with #': '# सँग ट्याग गरिएका पोस्टहरू',
    'Posts from selected district': 'छानिएको जिल्लाका पोस्टहरू',
    'All Categories': 'सबै श्रेणीहरू',
    'Trending Topics': 'चर्चित विषयहरू',
    'Photo': 'फोटो',
    'Post photo': 'पोस्टको फोटो',
    'Like': 'मन पर्‍यो',
    'Comment': 'टिप्पणी',
    'Comments': 'टिप्पणीहरू',
    'Share': 'साझा गर्नुहोस्',
    'The feed is showing your district. Be the first to share something here, or browse posts from across Nepal.': 'फिडले तपाईंको जिल्ला देखाइरहेको छ। यहाँ सबैभन्दा पहिले केही साझा गर्नुहोस्, वा नेपालभरका पोस्टहरू हेर्नुहोस्।',
    'View all districts': 'सबै जिल्लाहरू हेर्नुहोस्',
    'No posts found': 'कुनै पोस्ट भेटिएन',
    'Be the first to share something!': 'सबैभन्दा पहिले केही साझा गर्नुहोस्!',
    'No posts in': 'यहाँ कुनै पोस्ट छैन:',
    'yet': 'अहिलेसम्म',
    'Click to view full size': 'पूरा आकारमा हेर्न क्लिक गर्नुहोस्',
    'AI Classified': 'एआईद्वारा वर्गीकृत',
    'Classified by AI': 'एआईद्वारा वर्गीकृत',
    'Has Photo': 'फोटो सहित',
    'No comments yet. Be the first to comment!': 'अहिलेसम्म कुनै टिप्पणी छैन। सबैभन्दा पहिले टिप्पणी गर्नुहोस्!',
    'Add Comment': 'टिप्पणी थप्नुहोस्',
    'Back to Feed': 'फिडमा फर्कनुहोस्',
    'Write a comment...': 'टिप्पणी लेख्नुहोस्...',
    'Nepali': 'नेपाली',
    'English': 'अंग्रेजी',

    # --- citizen dashboard ---
    'Welcome,': 'स्वागत छ,',
    'Select your district': 'आफ्नो जिल्ला छान्नुहोस्',
    'Road Segments': 'सडक खण्डहरू',
    'Recent Posts': 'हालका पोस्टहरू',
    'Nationwide': 'राष्ट्रव्यापी',
    'Road Status': 'सडक अवस्था',
    'River Status': 'नदी अवस्था',
    'Development Projects': 'विकास आयोजनाहरू',
    'View All Roads': 'सबै सडक हेर्नुहोस्',
    'View All Rivers': 'सबै नदी हेर्नुहोस्',
    'View All Projects': 'सबै आयोजना हेर्नुहोस्',
    'No road data available.': 'सडक डाटा उपलब्ध छैन।',
    'No river data available.': 'नदी डाटा उपलब्ध छैन।',
    'No projects available.': 'कुनै आयोजना उपलब्ध छैन।',
    'View Post': 'पोस्ट हेर्नुहोस्',
    'No posts yet.': 'अहिलेसम्म कुनै पोस्ट छैन।',
    'Create First Post': 'पहिलो पोस्ट सिर्जना गर्नुहोस्',

    # --- districts ---
    "Nepal's 77 Districts": 'नेपालका ७७ जिल्लाहरू',
    'Select your district to see local information': 'स्थानीय जानकारी हेर्न आफ्नो जिल्ला छान्नुहोस्',

    # --- projects ---
    'Development Project Tracker': 'विकास आयोजना ट्र्याकर',
    'Track development projects across Nepal': 'नेपालभरका विकास आयोजनाहरू ट्र्याक गर्नुहोस्',
    'Project Details': 'आयोजना विवरण',
    'Progress Updates': 'प्रगति अपडेटहरू',
    'No updates yet.': 'अहिलेसम्म कुनै अपडेट छैन।',
    'Total Budget': 'कुल बजेट',
    'Spent': 'खर्च',
    'Complete': 'सम्पन्न',

    # --- roads and rivers ---
    'Live Road Status': 'प्रत्यक्ष सडक अवस्था',
    'Real-time road conditions across Nepal': 'नेपालभरको वास्तविक समयको सडक अवस्था',
    'Monitor river levels and flood risks': 'नदीको सतह र बाढीको जोखिम अनुगमन गर्नुहोस्',
    'of danger level': 'खतरा सतहको',

    # --- travel ---
    'Travel Planner': 'यात्रा योजना',
    'Plan your journey with live road and river information': 'प्रत्यक्ष सडक र नदी जानकारीसहित आफ्नो यात्रा योजना बनाउनुहोस्',
    'Plan Your Journey': 'आफ्नो यात्रा योजना बनाउनुहोस्',
    'From': 'बाट',
    'To': 'सम्म',
    'Travel Date': 'यात्रा मिति',
    'Preferred Time': 'रुचाइएको समय',
    'Flexible': 'लचिलो',
    'Morning (6AM - 10AM)': 'बिहान (६ - १० बजे)',
    'Afternoon (10AM - 4PM)': 'दिउँसो (१० - ४ बजे)',
    'Evening (4PM - 8PM)': 'साँझ (४ - ८ बजे)',
    'Analyze Route': 'मार्ग विश्लेषण गर्नुहोस्',
    'e.g., Sindhuli': 'जस्तै, सिन्धुली',
    'e.g., Kathmandu': 'जस्तै, काठमाडौं',
    'Travel Analysis': 'यात्रा विश्लेषण',
    'Travel Score': 'यात्रा अंक',
    'Risk Score': 'जोखिम अंक',
    'Est. Travel Time': 'अनुमानित यात्रा समय',
    'Active Warnings': 'सक्रिय चेतावनीहरू',
    'Road Conditions': 'सडक अवस्था',
    'River Conditions': 'नदी अवस्था',
    'Plan Another Trip': 'अर्को यात्रा योजना बनाउनुहोस्',

    # --- landing ---
    'Sign in': 'लगइन',
    'Get started': 'सुरु गर्नुहोस्',
    'Live across 77 districts': '७७ वटै जिल्लामा प्रत्यक्ष',
    'Know your district.': 'आफ्नो जिल्ला जान्नुहोस्।',
    'Before you travel.': 'यात्रा गर्नुअघि।',
    'Road closures, river levels, and infrastructure projects for every district in Nepal — reported by the people who live there, verified by the authorities who maintain them.': 'नेपालका हरेक जिल्लाका सडक बन्द, नदीको सतह र पूर्वाधार आयोजनाहरू — त्यहीँ बस्ने मानिसहरूले जानकारी दिने, र सम्बन्धित निकायले प्रमाणित गर्ने।',
    'Create free account': 'निःशुल्क खाता खोल्नुहोस्',
    'Create account': 'खाता खोल्नुहोस्',
    'Districts covered': 'समेटिएका जिल्लाहरू',
    'Provinces': 'प्रदेशहरू',
    'Languages': 'भाषाहरू',
    'Community reporting': 'सामुदायिक रिपोर्टिङ',
    'Everything about your district, in one place': 'आफ्नो जिल्लाको सबै जानकारी, एकै ठाउँमा',
    'Built for people who need to know whether the road is open before they set out.': 'हिँड्नुअघि बाटो खुला छ कि छैन थाहा पाउनुपर्नेहरूका लागि बनाइएको।',
    'Road status': 'सडक अवस्था',
    'Segment-level conditions across highways and feeder roads, with closures and construction flagged as they happen.': 'राजमार्ग र सहायक सडकहरूको खण्डगत अवस्था, बन्द र निर्माण भइरहेकै समयमा जनाइने।',
    'River monitoring': 'नदी अनुगमन',
    'Water levels and flood warnings for the rivers that cut through your district, updated through the monsoon.': 'तपाईंको जिल्ला हुँदै बग्ने नदीहरूको सतह र बाढी चेतावनी, मनसुनभरि अद्यावधिक हुने।',
    'Project tracking': 'आयोजना ट्र्याकिङ',
    'Follow bridges, roads, and public works from budget to completion — with real progress, not press releases.': 'पुल, सडक र सार्वजनिक निर्माणलाई बजेटदेखि सम्पन्न हुँदासम्म हेर्नुहोस् — प्रेस विज्ञप्ति होइन, वास्तविक प्रगतिसहित।',
    'Direct complaints': 'सीधा उजुरी',
    'File an issue against the responsible authority and track its status until somebody answers for it.': 'जिम्मेवार निकायविरुद्ध समस्या दर्ता गर्नुहोस् र जवाफ नआउन्जेल त्यसको अवस्था ट्र्याक गर्नुहोस्।',
    'Check a route end to end before you leave, with a risk score built from current road and river conditions.': 'हिँड्नुअघि पूरा मार्ग जाँच्नुहोस्, हालको सडक र नदी अवस्थाबाट बनेको जोखिम अंकसहित।',
    'AI assistant': 'एआई सहायक',
    'Ask about conditions in plain Nepali or English and get an answer drawn from live district data.': 'सामान्य नेपाली वा अंग्रेजीमा अवस्थाबारे सोध्नुहोस् र प्रत्यक्ष जिल्ला डाटामा आधारित जवाफ पाउनुहोस्।',
    'How it works': 'यसले कसरी काम गर्छ',
    'Three steps from signing up to knowing what is happening on the ground.': 'दर्ता गरेदेखि जमिनमा के भइरहेको छ थाहा पाउनसम्म तीन चरण।',
    'Pick your district': 'आफ्नो जिल्ला छान्नुहोस्',
    'Choose where you live or where you are heading. Everything you see is filtered to that district.': 'आफू बस्ने वा जाने ठाउँ छान्नुहोस्। तपाईंले देख्ने सबै जानकारी त्यही जिल्लाको हुनेछ।',
    'See live conditions': 'प्रत्यक्ष अवस्था हेर्नुहोस्',
    'Roads, rivers, and projects on one dashboard, combining community reports with authority updates.': 'सडक, नदी र आयोजनाहरू एउटै ड्यासबोर्डमा, सामुदायिक रिपोर्ट र निकायका अपडेट सँगै।',
    'Report and follow up': 'जानकारी दिनुहोस् र पछ्याउनुहोस्',
    'Post what you see, file complaints, and track them through to a response.': 'आफूले देखेको पोस्ट गर्नुहोस्, उजुरी दर्ता गर्नुहोस् र जवाफ नआउन्जेल पछ्याउनुहोस्।',
    'Start with your district': 'आफ्नो जिल्लाबाट सुरु गर्नुहोस्',
    'Free to use, in Nepali, Newari, Maithili, and English.': 'निःशुल्क, नेपाली, नेवारी, मैथिली र अंग्रेजीमा उपलब्ध।',
    'District intelligence for Nepal': 'नेपालका लागि जिल्ला जानकारी',
    'NepalSathi — District Intelligence for Nepal': 'नेपालसाथी — नेपालका लागि जिल्ला जानकारी',

    # --- flashed messages ---
    'No authority is linked to your account. Contact an administrator.': 'तपाईंको खातामा कुनै निकाय जोडिएको छैन। प्रशासकलाई सम्पर्क गर्नुहोस्।',
    'Authority account required.': 'निकाय खाता आवश्यक छ।',
    'Invalid username or password.': 'प्रयोगकर्ता नाम वा पासवर्ड मिलेन।',
    'Registration successful! Please login.': 'दर्ता सफल भयो! कृपया लगइन गर्नुहोस्।',
    'Welcome to Authority Panel!': 'निकाय प्यानलमा स्वागत छ!',
    'Authority account created! Please login.': 'निकाय खाता बन्यो! कृपया लगइन गर्नुहोस्।',
    'You have been logged out.': 'तपाईं लगआउट हुनुभयो।',
    'All fields are required.': 'सबै विवरण भर्नु आवश्यक छ।',
    'Username already exists.': 'यो प्रयोगकर्ता नाम पहिले नै छ।',
    'Email already registered.': 'यो इमेल पहिले नै दर्ता भइसकेको छ।',
    'This account is not an authority account.': 'यो खाता निकाय खाता होइन।',
    'Project updated!': 'आयोजना अद्यावधिक भयो!',
    'Road status updated!': 'सडक अवस्था अद्यावधिक भयो!',
    'River status updated!': 'नदी अवस्था अद्यावधिक भयो!',
    'Rs.': 'रु.',
    'Cr': 'करोड',
    'User #': 'प्रयोगकर्ता #',
    'Complaint Detail': 'उजुरी विवरण',
    'Test Posts': 'परीक्षण पोस्टहरू',
    'Crore': 'करोड',
    'AI Assistant': 'एआई सहायक',
    'AI Test': 'एआई परीक्षण',
    'Project Tracker': 'आयोजना ट्र्याकर',
    'unknown': 'अज्ञात',
    'Unknown': 'अज्ञात',
    'closed': 'बन्द',
    'under_construction': 'निर्माणाधीन',
    'planned': 'योजनामा',
    'Authority and description are required.': 'निकाय र विवरण अनिवार्य छ।',
    'Category and description are required.': 'श्रेणी र विवरण अनिवार्य छ।',
    'Comment added!': 'टिप्पणी थपियो!',
    'Current password is incorrect.': 'हालको पासवर्ड मिलेन।',
    'District selected successfully!': 'जिल्ला सफलतापूर्वक छानियो!',
    'Incident reported successfully!': 'घटना सफलतापूर्वक जाहेर गरियो!',
    'New passwords do not match.': 'नयाँ पासवर्डहरू मिलेनन्।',
    'No authority found for your account.': 'तपाईंको खाताको लागि कुनै निकाय भेटिएन।',
    'Password changed successfully!': 'पासवर्ड सफलतापूर्वक परिवर्तन भयो!',
    'Password must be at least 6 characters.': 'पासवर्ड कम्तीमा ६ अक्षरको हुनुपर्छ।',
    'Please enter both locations.': 'कृपया दुवै स्थान लेख्नुहोस्।',
    'Post content is required.': 'पोस्टको सामग्री अनिवार्य छ।',
    'Profile updated successfully!': 'प्रोफाइल सफलतापूर्वक अद्यावधिक भयो!',
    'Project updated successfully!': 'आयोजना सफलतापूर्वक अद्यावधिक भयो!',
    'Response sent successfully!': 'जवाफ सफलतापूर्वक पठाइयो!',
    'River status updated successfully!': 'नदी अवस्था सफलतापूर्वक अद्यावधिक भयो!',
    'Unsupported language': 'यो भाषा समर्थित छैन',
    'Username already taken.': 'यो प्रयोगकर्ता नाम पहिले नै लिइएको छ।',
    # --- notifications (M03) ---
    'Notifications': 'सूचनाहरू',
    'unread': 'नपढिएको',
    'Mark all as read': 'सबै पढिएको चिन्ह लगाउनुहोस्',
    'Mark as read': 'पढिएको चिन्ह लगाउनुहोस्',
    'View': 'हेर्नुहोस्',
    'No notifications yet.': 'अहिलेसम्म कुनै सूचना छैन।',
    'earthquake': 'भूकम्प',
    'road_damage': 'सडक क्षति',
    # --- citizen reports (M05) ---
    'Report a Hazard': 'जोखिम रिपोर्ट गर्नुहोस्',
    'My Reports': 'मेरा रिपोर्टहरू',
    'Send a photo of a landslide or road damage. Authorities will review it.': 'पहिरो वा सडक क्षतिको फोटो पठाउनुहोस्। निकायले यसको समीक्षा गर्नेछ।',
    'What did you see?': 'तपाईंले के देख्नुभयो?',
    'Take a photo or choose one. JPG, PNG or WEBP, up to': 'फोटो खिच्नुहोस् वा छान्नुहोस्। JPG, PNG वा WEBP, अधिकतम',
    'Use My Location': 'मेरो स्थान प्रयोग गर्नुहोस्',
    'Latitude': 'अक्षांश',
    'Longitude': 'देशान्तर',
    'Optional. If location access is blocked, type the coordinates or leave them empty.': 'वैकल्पिक। स्थान पहुँच बन्द भए निर्देशांक लेख्नुहोस् वा खाली छोड्नुहोस्।',
    'Nearby landmark (optional)': 'नजिकको चिनारी स्थान (वैकल्पिक)',
    'e.g., near the bridge at Kamalamai': 'जस्तै, कमलामाईको पुल नजिक',
    'Shown publicly with the hazard.': 'यो जोखिमसँगै सार्वजनिक रूपमा देखिन्छ।',
    'Description (optional)': 'विवरण (वैकल्पिक)',
    'Only you and the reviewing authority can see this.': 'यो तपाईं र समीक्षा गर्ने निकायले मात्र देख्न सक्छन्।',
    'Submit Report': 'रिपोर्ट पठाउनुहोस्',
    'Getting location…': 'स्थान लिँदै…',
    'Location added.': 'स्थान थपियो।',
    'Location unavailable. You can type it or leave it empty.': 'स्थान उपलब्ध भएन। तपाईं लेख्न वा खाली छोड्न सक्नुहुन्छ।',
    'Please add a photo.': 'कृपया फोटो थप्नुहोस्।',
    'Sending…': 'पठाउँदै…',
    'Could not send the report. Please try again.': 'रिपोर्ट पठाउन सकिएन। फेरि प्रयास गर्नुहोस्।',
    'Report sent. Thank you — authorities will review it.': 'रिपोर्ट पठाइयो। धन्यवाद — निकायले समीक्षा गर्नेछ।',
    'Report photo': 'रिपोर्टको फोटो',
    'Hazard': 'जोखिम',
    'You have not sent any reports yet.': 'तपाईंले अहिलेसम्म कुनै रिपोर्ट पठाउनुभएको छैन।',
    'submitted': 'पेश गरियो',
    'accepted': 'स्वीकृत',
    'detected': 'पत्ता लाग्यो',
    'investigating': 'अनुसन्धान हुँदै',
    'confirmed': 'पुष्टि भयो',
    # --- photo report review (M06) ---
    'Review Photo Reports': 'फोटो रिपोर्ट समीक्षा',
    'AI analysis is evidence only. It never accepts a report or changes a hazard. You decide.': 'एआई विश्लेषण प्रमाण मात्र हो। यसले रिपोर्ट स्वीकार गर्दैन वा जोखिम परिवर्तन गर्दैन। निर्णय तपाईंको हो।',
    'Citizen report': 'नागरिकको रिपोर्ट',
    'AI analysis': 'एआई विश्लेषण',
    'differs from citizen': 'नागरिकको भन्दा फरक',
    'Model confidence': 'मोडेलको विश्वास अंक',
    'Analysis failed. Review the photo manually.': 'विश्लेषण असफल भयो। फोटो आफैं समीक्षा गर्नुहोस्।',
    'Not analyzed': 'विश्लेषण गरिएको छैन',
    'Hazard event': 'जोखिम घटना',
    'Accept': 'स्वीकार गर्नुहोस्',
    'Reject': 'अस्वीकार गर्नुहोस्',
    'Run analysis again': 'फेरि विश्लेषण गर्नुहोस्',
    'No photo reports to review.': 'समीक्षा गर्न कुनै फोटो रिपोर्ट छैन।',
    # --- disaster monitoring dashboard (M07) ---
    'Disaster Monitoring': 'विपद् अनुगमन',
    'Road damage': 'सडक क्षति',
    # --- authority response (M09) ---
    'response': 'प्रतिकार्य जारी',
    'Investigating': 'अनुसन्धान हुँदै',
    'Confirmed': 'पुष्टि भयो',
    'Response in progress': 'प्रतिकार्य जारी',
    'Open response': 'प्रतिकार्य खोल्नुहोस्',
    'notes': 'टिप्पणी',
    'open actions': 'खुला कार्य',
    'Hazard response': 'जोखिम प्रतिकार्य',
    'Lifecycle': 'जीवनचक्र',
    'Note': 'टिप्पणी',
    'required to resolve or reject': 'समाधान वा अस्वीकार गर्न आवश्यक',
    'Start Investigation': 'अनुसन्धान सुरु गर्नुहोस्',
    'Confirm Hazard': 'जोखिम पुष्टि गर्नुहोस्',
    'Start Response': 'प्रतिकार्य सुरु गर्नुहोस्',
    'Resolve Incident': 'घटना समाधान गर्नुहोस्',
    'Reject Hazard': 'जोखिम अस्वीकार गर्नुहोस्',
    'This incident is closed. Resolved and rejected incidents cannot be reopened.': 'यो घटना बन्द छ। समाधान वा अस्वीकृत घटनाहरू फेरि खोल्न मिल्दैन।',
    'Timeline': 'समयरेखा',
    'Hazard detected': 'जोखिम पत्ता लाग्यो',
    'Investigation note': 'अनुसन्धान टिप्पणी',
    'Response action': 'प्रतिकार्य',
    'Add investigation note': 'अनुसन्धान टिप्पणी थप्नुहोस्',
    'Add note': 'टिप्पणी थप्नुहोस्',
    'Response actions': 'प्रतिकार्यहरू',
    'Completed': 'सम्पन्न',
    'No response actions yet.': 'अहिलेसम्म कुनै प्रतिकार्य छैन।',
    'Add response action': 'प्रतिकार्य थप्नुहोस्',
    'What is being done?': 'के गरिँदैछ?',
    'Add action': 'कार्य थप्नुहोस्',
    'Risk assessment (M08 evidence)': 'जोखिम मूल्याङ्कन (M08 प्रमाण)',
    'Sources': 'स्रोतहरू',
    'Evidence only: the assessment never confirms or resolves a hazard.': 'प्रमाण मात्र: मूल्याङ्कनले जोखिम पुष्टि वा समाधान गर्दैन।',
    'A note is required to resolve or reject.': 'समाधान वा अस्वीकार गर्न टिप्पणी आवश्यक छ।',
    'All districts': 'सबै जिल्ला',
    'Refresh': 'ताजा गर्नुहोस्',
    'Active hazards': 'सक्रिय जोखिमहरू',
    'Map': 'नक्सा',
    'Map of active hazards': 'सक्रिय जोखिमहरूको नक्सा',
    'Hazard list': 'जोखिम सूची',
    'IoT devices': 'आईओटी उपकरणहरू',
    'Sensor readings are telemetry only. A vibration or tilt value is not an earthquake detection.': 'सेन्सर रिडिङ टेलिमेट्री मात्र हो। कम्पन वा झुकावको मानले भूकम्प पत्ता लागेको जनाउँदैन।',
    'Citizen photo reports': 'नागरिक फोटो रिपोर्टहरू',
    'AI analysis is evidence only. It never confirms a hazard or changes its severity.': 'एआई विश्लेषण प्रमाण मात्र हो। यसले जोखिम पुष्टि गर्दैन वा गम्भीरता परिवर्तन गर्दैन।',
    'My alerts': 'मेरा सूचनाहरू',
    'System statistics': 'प्रणाली तथ्याङ्क',
    'Earthquake / abnormal ground motion': 'भूकम्प / असामान्य भू-कम्पन',
    'Online': 'अनलाइन',
    'Stale': 'पुरानो डेटा',
    'Offline': 'अफलाइन',
    'Never reported': 'कहिल्यै रिपोर्ट गरेन',
    'Water level': 'पानीको सतह',
    'Temperature': 'तापक्रम',
    'Humidity': 'आर्द्रता',
    'Vibration': 'कम्पन',
    'Tilt': 'झुकाव',
    'Rainfall': 'वर्षा',
    'No active hazards.': 'कुनै सक्रिय जोखिम छैन।',
    'No devices visible to you.': 'तपाईंले हेर्न मिल्ने कुनै उपकरण छैन।',
    'No photo reports.': 'कुनै फोटो रिपोर्ट छैन।',
    'No readings yet': 'अहिलेसम्म रिडिङ छैन',
    'Affected': 'प्रभावित',
    'Source': 'स्रोत',
    'Detected': 'पत्ता लागेको',
    'Updated': 'अद्यावधिक',
    'Last seen': 'अन्तिम पटक देखिएको',
    'ago': 'अघि',
    'min': 'मिनेट',
    'Disabled': 'निष्क्रिय',
    'AI': 'एआई',
    'Analysis failed': 'विश्लेषण असफल',
    'Not on the map (no coordinates):': 'नक्सामा छैन (निर्देशांक छैन):',
    'refreshes every': 'प्रत्येक पटक ताजा हुन्छ:',
    'paused while tab is hidden': 'ट्याब लुकेको बेला रोकिएको छ',
    'Could not load dashboard data.': 'ड्यासबोर्ड डेटा लोड गर्न सकिएन।',
    'Your account is not linked to an authority district.': 'तपाईंको खाता कुनै निकायको जिल्लासँग जोडिएको छैन।',
    'Online = reported within': 'अनलाइन = यति समयभित्र रिपोर्ट गरेको:',
    'stale = within': 'पुरानो = यति समयभित्र:',
    'Events': 'घटनाहरू',
    'Reports': 'रिपोर्टहरू',
    'Notifications (24 h)': 'सूचनाहरू (२४ घण्टा)',
    'Devices': 'उपकरणहरू',
    'Total': 'जम्मा',
    'IoT': 'आईओटी',
    'System': 'प्रणाली',
    # --- product quality: accounts, dashboards, design system ---
    '3-30 letters, digits, dots, dashes or underscores': '३-३० अक्षर, अङ्क, थोप्लो, ड्यास वा अन्डरस्कोर',
    'About NepalSathi': 'नेपालसाथीबारे',
    'Accounts are issued by an administrator.': 'खाता प्रशासकले जारी गर्छन्।',
    'Active hazards affecting': 'सक्रिय जोखिम प्रभावित',
    'Active hazards in your district': 'तपाईंको जिल्लाका सक्रिय जोखिमहरू',
    'Active hazards in your jurisdiction': 'तपाईंको क्षेत्राधिकारका सक्रिय जोखिमहरू',
    'Active hazards now': 'हाल सक्रिय जोखिम',
    'Alerts and local information are based on your home district.': 'सूचना र स्थानीय जानकारी तपाईंको गृह जिल्लामा आधारित हुन्छन्।',
    'Alerts for floods, landslides and road damage where you live': 'तपाईं बस्ने ठाउँमा बाढी, पहिरो र सडक क्षतिको सूचना',
    'All': 'सबै',
    'All roads': 'सबै सडक',
    'At least 8 characters': 'कम्तीमा ८ अक्षर',
    'Attribution': 'श्रेय',
    'Authorities investigate, confirm, respond and resolve — every step recorded.': 'निकायले अनुसन्धान, पुष्टि, प्रतिकार्य र समाधान गर्छ — हरेक चरण अभिलेख हुन्छ।',
    'Authority accounts are created by an administrator.': 'निकायका खाता प्रशासकले बनाउँछन्।',
    'Authority panel': 'निकाय प्यानल',
    'Authority response': 'निकायको प्रतिकार्य',
    'Authority sign in': 'निकाय लगइन',
    'Awaiting investigation': 'अनुसन्धान पर्खँदै',
    'Back to profile': 'प्रोफाइलमा फर्कनुहोस्',
    'Choose a valid district': 'मान्य जिल्ला छान्नुहोस्',
    'Choose a valid district.': 'मान्य जिल्ला छान्नुहोस्।',
    'Choose your district': 'आफ्नो जिल्ला छान्नुहोस्',
    'Choose your district to see local hazards, rivers and roads.': 'स्थानीय जोखिम, नदी र सडक हेर्न आफ्नो जिल्ला छान्नुहोस्।',
    'Citizen account': 'नागरिक खाता',
    'Citizen photos, checked by AI as evidence and reviewed by authorities.': 'नागरिकका फोटो, एआईले प्रमाणका रूपमा जाँचेका र निकायले समीक्षा गरेका।',
    'Citizen sign in': 'नागरिक लगइन',
    'Community posts': 'सामुदायिक पोस्टहरू',
    'Confirm password': 'पासवर्ड पुष्टि गर्नुहोस्',
    'Contact': 'सम्पर्क',
    'Current location': 'हालको स्थान',
    'Delete my saved location': 'मेरो सुरक्षित स्थान मेटाउनुहोस्',
    'Describe where you are now': 'तपाईं अहिले कहाँ हुनुहुन्छ, लेख्नुहोस्',
    'Detecting your location…': 'तपाईंको स्थान पत्ता लगाउँदै…',
    'Device': 'उपकरण',
    'Disaster intelligence': 'विपद् सूचना प्रणाली',
    'District details': 'जिल्ला विवरण',
    'Districts of Nepal': 'नेपालका जिल्लाहरू',
    'Enter a valid email address': 'मान्य इमेल ठेगाना लेख्नुहोस्',
    'Enter the mobile number in international form, e.g. +977 98XXXXXXXX': 'मोबाइल नम्बर अन्तर्राष्ट्रिय ढाँचामा लेख्नुहोस्, जस्तै +977 98XXXXXXXX',
    'Evidence from sensors and citizens becomes a hazard event only after X-MAN assesses it, and authorities confirm and resolve it.': 'सेन्सर र नागरिकका प्रमाण X-MAN ले मूल्याङ्कन गरेपछि मात्र जोखिम घटना बन्छन्, र निकायले पुष्टि तथा समाधान गर्छन्।',
    'Example alert': 'उदाहरण सूचना',
    'Find a district': 'जिल्ला खोज्नुहोस्',
    'Finding your location took too long. Try again, or skip this step.': 'स्थान पत्ता लगाउन धेरै समय लाग्यो। फेरि प्रयास गर्नुहोस् वा यो चरण छोड्नुहोस्।',
    'Flood, landslide, road-damage and ground-motion alerts for your district, built from river sensors, citizen photo reports and authority updates — with every alert reviewed by a responsible authority.': 'नदी सेन्सर, नागरिकका फोटो रिपोर्ट र निकायका अद्यावधिकबाट बनेका तपाईंको जिल्लाका बाढी, पहिरो, सडक क्षति र भू-कम्पन सूचना — हरेक सूचना जिम्मेवार निकायले समीक्षा गर्छ।',
    'Floods': 'बाढी',
    'Footer': 'फुटर',
    'Freshness': 'ताजापन',
    'Full name': 'पूरा नाम',
    'Hazard alerts': 'जोखिम सूचना',
    'Hazards, rivers and roads on one dashboard, combining sensors, community reports and authority updates.': 'सेन्सर, सामुदायिक रिपोर्ट र निकायका अद्यावधिक मिलाएर एउटै ड्यासबोर्डमा जोखिम, नदी र सडक।',
    'Hide': 'लुकाउनुहोस्',
    'Identity': 'परिचय',
    'Know what is happening in your district.': 'आफ्नो जिल्लामा के भइरहेको छ, थाहा पाउनुहोस्।',
    'Landslide confirmed': 'पहिरो पुष्टि भयो',
    'Landslides': 'पहिरो',
    'Latest readings': 'पछिल्लो रिडिङ',
    'Latitude and longitude must be provided together': 'अक्षांश र देशान्तर सँगै दिनुपर्छ',
    'Level': 'सतह',
    'Local hazard status': 'स्थानीय जोखिम अवस्था',
    'Local map': 'स्थानीय नक्सा',
    'Location coordinates are out of range': 'स्थानका निर्देशांक दायराबाहिर छन्',
    'Location coordinates must be numbers': 'स्थानका निर्देशांक अङ्क हुनुपर्छ',
    'Location detected': 'स्थान पत्ता लाग्यो',
    'Location needs a secure (HTTPS) connection on this device. You can skip this step.': 'यो उपकरणमा स्थानका लागि सुरक्षित (HTTPS) जडान चाहिन्छ। तपाईं यो चरण छोड्न सक्नुहुन्छ।',
    'Location permission was denied. You can allow it in your browser settings and try again, or skip this step.': 'स्थान अनुमति अस्वीकार भयो। ब्राउजर सेटिङमा अनुमति दिएर फेरि प्रयास गर्नुहोस् वा यो चरण छोड्नुहोस्।',
    'Location removed.': 'स्थान हटाइयो।',
    'Map of hazards with known coordinates': 'ज्ञात निर्देशांक भएका जोखिमहरूको नक्सा',
    'Mobile number': 'मोबाइल नम्बर',
    'Mobile number is required': 'मोबाइल नम्बर आवश्यक छ',
    'Mobile number may only contain digits, spaces, dashes and a leading +': 'मोबाइल नम्बरमा अङ्क, खाली ठाउँ, ड्यास र सुरुमा + मात्र हुन सक्छ',
    'My photo reports': 'मेरा फोटो रिपोर्ट',
    'My reports': 'मेरा रिपोर्ट',
    'Namaste': 'नमस्ते',
    'Nationwide active hazards': 'देशभरका सक्रिय जोखिम',
    'Nepal mobile numbers have 10 digits and start with 96, 97 or 98': 'नेपालका मोबाइल नम्बर १० अङ्कका हुन्छन् र 96, 97 वा 98 बाट सुरु हुन्छन्',
    'Nepal mobile, or +country code. Kept private; for future emergency SMS.': 'नेपाली मोबाइल, वा +देश कोड। गोप्य राखिन्छ; भविष्यका आपतकालीन SMS का लागि।',
    'No active hazards in this district.': 'यो जिल्लामा कुनै सक्रिय जोखिम छैन।',
    'No active hazards in your district right now.': 'अहिले तपाईंको जिल्लामा कुनै सक्रिय जोखिम छैन।',
    'No district matches that name.': 'त्यो नाम मिल्ने कुनै जिल्ला छैन।',
    'No hazard here has map coordinates yet. Hazards reported with GPS appear on the map.': 'यहाँका कुनै जोखिमको नक्सा निर्देशांक छैन। GPS सहित रिपोर्ट गरिएका जोखिम नक्सामा देखिन्छन्।',
    'No location saved. Sharing it is optional and separate from your permanent address.': 'कुनै स्थान सुरक्षित छैन। यो दिनु वैकल्पिक हो र स्थायी ठेगानाभन्दा छुट्टै हो।',
    'No rivers recorded for this district.': 'यो जिल्लाका कुनै नदी अभिलेखमा छैनन्।',
    'Not verified': 'प्रमाणित छैन',
    'Nothing to report here.': 'यहाँ रिपोर्ट गर्नुपर्ने केही छैन।',
    'One alert per event and severity change, sent to the districts it affects — never one per sensor reading.': 'हरेक घटना र गम्भीरता परिवर्तनमा एउटा सूचना, प्रभावित जिल्लाहरूमा — हरेक सेन्सर रिडिङमा होइन।',
    'Open response actions': 'खुला प्रतिकार्यहरू',
    'Operational access for district authorities.': 'जिल्ला निकायका लागि सञ्चालन पहुँच।',
    'Operational map': 'सञ्चालन नक्सा',
    'Permanent address': 'स्थायी ठेगाना',
    'Photo credits': 'फोटो श्रेय',
    'Photo reports': 'फोटो रिपोर्ट',
    'Photo reports to review': 'समीक्षा गर्नुपर्ने फोटो रिपोर्ट',
    'Please fix the highlighted fields.': 'चिन्ह लगाइएका क्षेत्र सच्याउनुहोस्।',
    'Population': 'जनसंख्या',
    'Private details': 'गोप्य विवरण',
    'Private: only you and administrators see this': 'गोप्य: तपाईं र प्रशासकले मात्र देख्छन्',
    'Recent alerts': 'हालका सूचनाहरू',
    'Remove location': 'स्थान हटाउनुहोस्',
    'Report a landslide or damaged road from your phone. Your photo, address and location stay private.': 'फोनबाट पहिरो वा बिग्रिएको सडक रिपोर्ट गर्नुहोस्। तपाईंको फोटो, ठेगाना र स्थान गोप्य रहन्छन्।',
    'Report hazards with a photo; authorities review every report': 'फोटोसहित जोखिम रिपोर्ट गर्नुहोस्; निकायले हरेक रिपोर्ट समीक्षा गर्छ',
    'Reported from the road with GPS, so the right district is alerted.': 'सडकबाटै GPS सहित रिपोर्ट गरिन्छ, ताकि सही जिल्लालाई सूचना जाओस्।',
    'Review': 'समीक्षा',
    'River': 'नदी',
    'River level rising': 'नदीको सतह बढ्दै',
    "River water-level sensors compare readings with each river's danger mark.": 'नदीका जलसतह सेन्सरले रिडिङलाई हरेक नदीको खतराको चिन्हसँग दाँज्छन्।',
    'Rivers and roads': 'नदी र सडक',
    'SMS verification is not available yet.': 'SMS प्रमाणीकरण अहिले उपलब्ध छैन।',
    'Save': 'सुरक्षित गर्नुहोस्',
    'Saved': 'सुरक्षित',
    'Send a photo of what you see and follow it until an authority reviews it.': 'देखेको कुराको फोटो पठाउनुहोस् र निकायले समीक्षा नगरेसम्म पछ्याउनुहोस्।',
    'Set as my district': 'मेरो जिल्ला बनाउनुहोस्',
    'Set your district': 'आफ्नो जिल्ला तोक्नुहोस्',
    'Set your district above to see its hazard status.': 'जोखिम अवस्था हेर्न माथि आफ्नो जिल्ला तोक्नुहोस्।',
    'Share where you are now so alerts can reach you. Your browser will ask for permission. This is separate from your permanent address.': 'सूचना तपाईंसम्म पुगोस् भनेर अहिलेको स्थान दिनुहोस्। ब्राउजरले अनुमति माग्नेछ। यो स्थायी ठेगानाभन्दा छुट्टै हो।',
    'Show': 'देखाउनुहोस्',
    'Site photographs come from Wikimedia Commons under the licences below. Citizen report photos are private and never used here.': 'साइटका फोटो तलका इजाजतपत्रअन्तर्गत विकिमिडिया कमन्सबाट लिइएका हुन्। नागरिक रिपोर्टका फोटो गोप्य छन् र यहाँ कहिल्यै प्रयोग हुँदैनन्।',
    'Skip to main content': 'मुख्य सामग्रीमा जानुहोस्',
    'Stored for future emergency SMS alerts. Changing it resets verification.': 'भविष्यका आपतकालीन SMS सूचनाका लागि राखिन्छ। परिवर्तन गर्दा प्रमाणीकरण हट्छ।',
    'That username, email or mobile number was just taken.': 'त्यो प्रयोगकर्ता नाम, इमेल वा मोबाइल नम्बर भर्खरै लिइयो।',
    'The hazards X-MAN watches': 'X-MAN ले निगरानी गर्ने जोखिमहरू',
    'This browser cannot share location. You can skip this step.': 'यो ब्राउजरले स्थान दिन सक्दैन। तपाईं यो चरण छोड्न सक्नुहुन्छ।',
    'This email is already registered': 'यो इमेल पहिल्यै दर्ता छ',
    'This mobile number is already registered': 'यो मोबाइल नम्बर पहिल्यै दर्ता छ',
    'This username is already taken': 'यो प्रयोगकर्ता नाम पहिल्यै लिइसकिएको छ',
    'Try again': 'फेरि प्रयास गर्नुहोस्',
    'Unread alerts': 'नपढिएका सूचना',
    'Use my current location': 'मेरो हालको स्थान प्रयोग गर्नुहोस्',
    'Username must be 3-30 letters, digits, dots, dashes or underscores': 'प्रयोगकर्ता नाम ३-३० अक्षर, अङ्क, थोप्लो, ड्यास वा अन्डरस्कोरको हुनुपर्छ',
    'Verified': 'प्रमाणित',
    'View all': 'सबै हेर्नुहोस्',
    'When a flood, landslide, road damage or abnormal ground motion is detected in your district, it appears here.': 'तपाईंको जिल्लामा बाढी, पहिरो, सडक क्षति वा असामान्य भू-कम्पन पत्ता लागेमा यहाँ देखिन्छ।',
    'Where you live': 'तपाईं बस्ने ठाउँ',
    'You': 'तपाईं',
    'Your dashboard': 'तपाईंको ड्यासबोर्ड',
    'Your district': 'तपाईंको जिल्ला',
    'Your district is now set.': 'तपाईंको जिल्ला तोकियो।',
    'Your language': 'तपाईंको भाषा',
    'Your location is unavailable right now. Try again, or skip this step.': 'तपाईंको स्थान अहिले उपलब्ध छैन। फेरि प्रयास गर्नुहोस् वा यो चरण छोड्नुहोस्।',
    'Your mobile number, address and location are private: only you and administrators can see them.': 'तपाईंको मोबाइल नम्बर, ठेगाना र स्थान गोप्य छन्: तपाईं र प्रशासकले मात्र देख्छन्।',
    'Your phone, address and location are never shown publicly': 'तपाईंको फोन, ठेगाना र स्थान कहिल्यै सार्वजनिक गरिँदैन',
    'accuracy about': 'शुद्धता करिब',
    'danger': 'खतरा',
    'districts': 'जिल्ला',
    'e.g., staying with family near Bardibas bus park': 'जस्तै, बर्दिबास बसपार्क नजिक परिवारसँग बसिरहेको',
    'highest severity': 'उच्चतम गम्भीरता',
    'optional': 'वैकल्पिक',
    'provinces': 'प्रदेश',
    'resized': 'आकार मिलाइएको',
    'segments': 'खण्ड',
    'total': 'जम्मा',
    # --- final QA ---
    'Invalid status.': 'अमान्य स्थिति।',
    'Progress must be a whole number from 0 to 100.': 'प्रगति ० देखि १०० सम्मको पूर्ण सङ्ख्या हुनुपर्छ।',
    'Invalid road status or traffic level.': 'सडकको स्थिति वा ट्राफिक स्तर अमान्य छ।',
    'Invalid water level (0-50 m) or status.': 'जलसतह (०-५० मि.) वा स्थिति अमान्य छ।',
    'Choose a district, an authority and a category, and describe the issue.': 'जिल्ला, निकाय र वर्ग छान्नुहोस्, अनि समस्याको विवरण लेख्नुहोस्।',
    'Water level must be a number from 0 to 50 m.': 'जलसतह ० देखि ५० मि. सम्मको सङ्ख्या हुनुपर्छ।',
    'No hazard recognised': 'कुनै जोखिम पहिचान भएन',
    'best match': 'सबैभन्दा नजिकको मिलान',
    'needs': 'आवश्यक',
    # --- M12: admin control center, emergency alerts, Web Push ---
    '{hazard} detected in {place}': '{place}मा {hazard} पत्ता लाग्यो',
    '{hazard} detected': '{hazard} पत्ता लाग्यो',
    '{hazard} escalated to {severity} in {place}': '{place}मा {hazard} {severity} स्तरमा बढ्यो',
    '{hazard} escalated to {severity}': '{hazard} {severity} स्तरमा बढ्यो',
    '{hazard} confirmed in {place}': '{place}मा {hazard} पुष्टि भयो',
    '{hazard} confirmed': '{hazard} पुष्टि भयो',
    '{hazard} resolved in {place}': '{place}मा {hazard} समाधान भयो',
    '{hazard} resolved': '{hazard} समाधान भयो',
    'X-MAN EMERGENCY ALERT': 'X-MAN आपतकालीन सूचना',
    'A short beep pattern while an emergency alert is shown on this website. It stops by itself and can be muted.': 'यो वेबसाइटमा आपतकालीन सूचना देखिँदा छोटो बिप ध्वनि बज्छ। यो आफैँ रोकिन्छ र बन्द गर्न सकिन्छ।',
    'Account status': 'खाताको स्थिति',
    'Accounts': 'खाताहरू',
    'Accounts, authorities and emergency notification delivery across all districts.': 'सबै जिल्लाका खाता, निकाय र आपतकालीन सूचना वितरण।',
    'Active': 'सक्रिय',
    'Active hazards in district': 'जिल्लाका सक्रिय जोखिम',
    'Active hazards in this district': 'यस जिल्लाका सक्रिय जोखिमहरू',
    'Active on this device': 'यो उपकरणमा सक्रिय',
    'Active subscriptions': 'सक्रिय सदस्यता',
    'Address': 'ठेगाना',
    'Admin': 'प्रशासन',
    'Admin Control Center': 'प्रशासन नियन्त्रण केन्द्र',
    'Admin sections': 'प्रशासन खण्डहरू',
    # --- Super Admin Control Center ---
    'Super Admin Control Center': 'सुपर एडमिन नियन्त्रण केन्द्र',
    'Super Admin': 'सुपर एडमिन',
    'Super Administrator': 'सुपर प्रशासक',
    'Super Admin sections': 'सुपर एडमिन खण्डहरू',
    'Super Admins': 'सुपर एडमिनहरू',
    'Super Admin accounts': 'सुपर एडमिन खाताहरू',
    'Users': 'प्रयोगकर्ताहरू',
    'Hazards': 'जोखिमहरू',
    'Audit log': 'लेखापरीक्षण लग',
    'Full audit log': 'पूरा लेखापरीक्षण लग',
    'System health': 'प्रणाली स्वास्थ्य',
    'Citizen reports': 'नागरिक रिपोर्टहरू',
    'IoT Device Control Center': 'IoT उपकरण नियन्त्रण केन्द्र',
    'IoT device': 'IoT उपकरण',
    'Administrative history': 'प्रशासनिक इतिहास',
    'Recent administrative actions': 'हालैका प्रशासनिक कार्यहरू',
    'Reason (recorded in the audit log)': 'कारण (लेखापरीक्षण लगमा रेकर्ड हुन्छ)',
    'What happens': 'के हुन्छ',
    'Type': 'टाइप गर्नुहोस्',
    'to continue': 'जारी राख्न',
    'Manage account': 'खाता व्यवस्थापन',
    'Authority access': 'निकाय पहुँच',
    'Deactivate authority': 'निकाय निष्क्रिय गर्नुहोस्',
    'Reactivate authority': 'निकाय पुनः सक्रिय गर्नुहोस्',
    'Re-enable account': 'खाता पुनः सक्रिय गर्नुहोस्',
    'Force password change': 'पासवर्ड परिवर्तन अनिवार्य गर्नुहोस्',
    'End all sessions': 'सबै सत्र अन्त्य गर्नुहोस्',
    'Disconnect (disable device)': 'विच्छेद (उपकरण निष्क्रिय)',
    'Connect (enable device)': 'जडान (उपकरण सक्रिय)',
    'Rotate API key': 'API कुञ्जी परिवर्तन गर्नुहोस्',
    'Device disabled by Super Admin.': 'सुपर एडमिनद्वारा उपकरण निष्क्रिय गरिएको छ।',
    'Offline — no telemetry received recently': 'अफलाइन — हालै कुनै टेलिमेट्री प्राप्त भएन',
    'Offline — no telemetry received recently.': 'अफलाइन — हालै कुनै टेलिमेट्री प्राप्त भएन।',
    'Disabled — telemetry refused': 'निष्क्रिय — टेलिमेट्री अस्वीकार',
    'Telemetry history': 'टेलिमेट्री इतिहास',
    'Administrative intervention': 'प्रशासनिक हस्तक्षेप',
    'Status history': 'स्थिति इतिहास',
    'Success': 'सफल',
    'Refused': 'अस्वीकृत',
    'Administration': 'प्रशासन',
    'Administrator': 'प्रशासक',
    'Affected area': 'प्रभावित क्षेत्र',
    'Alerts are sent for hazards affecting your registered district.': 'तपाईंको दर्ता गरिएको जिल्लालाई असर गर्ने जोखिमका सूचना पठाइन्छ।',
    'All accounts disabled': 'सबै खाता निष्क्रिय',
    'Allowed push services': 'अनुमति प्राप्त पुश सेवाहरू',
    'An administrator reset your password. Choose a new password to continue.': 'प्रशासकले तपाईंको पासवर्ड रिसेट गर्नुभयो। अगाडि बढ्न नयाँ पासवर्ड छान्नुहोस्।',
    'Any': 'कुनै पनि',
    'At least 8 characters.': 'कम्तीमा ८ अक्षर।',
    'Authority accounts': 'निकायका खाता',
    'Authority offices, their accounts, devices and emergency notification capability.': 'निकायका कार्यालय, तिनका खाता, उपकरण र आपतकालीन सूचना क्षमता।',
    'Back to authorities': 'निकायहरूमा फर्कनुहोस्',
    'Back to citizens': 'नागरिकहरूमा फर्कनुहोस्',
    'Browser permission': 'ब्राउजर अनुमति',
    'Browser push is not configured on this server. In-website alerts still work.': 'यो सर्भरमा ब्राउजर पुश कन्फिगर गरिएको छैन। वेबसाइटभित्रका सूचना भने काम गर्छन्।',
    'By district': 'जिल्लाअनुसार',
    'Citizens': 'नागरिकहरू',
    'Configured': 'कन्फिगर गरिएको',
    'Confirm temporary password': 'अस्थायी पासवर्ड पुष्टि गर्नुहोस्',
    'Controls district': 'जिम्मेवार जिल्ला',
    'Could not enable emergency alerts on this browser.': 'यो ब्राउजरमा आपतकालीन सूचना सक्रिय गर्न सकिएन।',
    'Created': 'सिर्जना',
    'Current location shared': 'हालको स्थान साझा गरिएको',
    'Denied': 'अस्वीकृत',
    'Devices with emergency alerts enabled:': 'आपतकालीन सूचना सक्रिय भएका उपकरण:',
    'Disable': 'निष्क्रिय पार्नुहोस्',
    'Disable account': 'खाता निष्क्रिय पार्नुहोस्',
    'Disabled subscriptions': 'निष्क्रिय सदस्यता',
    'Disabling signs the citizen out and blocks login. Their data and notification history are kept.': 'निष्क्रिय पार्दा नागरिक लगआउट हुन्छन् र लगइन रोकिन्छ। उनको डाटा र सूचना इतिहास राखिन्छ।',
    'Dismiss': 'हटाउनुहोस्',
    'District-wise citizen directory. Counts come from the database.': 'जिल्लाअनुसार नागरिक निर्देशिका। सङ्ख्या डाटाबेसबाट आउँछन्।',
    'Emergency alert permission (all users)': 'आपतकालीन सूचना अनुमति (सबै प्रयोगकर्ता)',
    'Emergency alert settings': 'आपतकालीन सूचना सेटिङ',
    'Emergency alerts': 'आपतकालीन सूचना',
    'Emergency alerts enabled.': 'आपतकालीन सूचना सक्रिय भयो।',
    'Emergency alerts turned off. Your notification history is unchanged.': 'आपतकालीन सूचना बन्द भयो। तपाईंको सूचना इतिहास जस्ताको तस्तै छ।',
    'Emergency disaster alert': 'आपतकालीन विपद् सूचना',
    'Emergency notification settings': 'आपतकालीन सूचना सेटिङ',
    'Emergency notification settings, push subscriptions and recent delivery.': 'आपतकालीन सूचना सेटिङ, पुश सदस्यता र हालको वितरण।',
    'Emergency notifications': 'आपतकालीन सूचना',
    'Emergency push': 'आपतकालीन पुश',
    'Emergency sound': 'आपतकालीन ध्वनि',
    'Emergency sound OFF': 'आपतकालीन ध्वनि बन्द',
    'Emergency sound ON': 'आपतकालीन ध्वनि चालु',
    'Emergency threshold': 'आपतकालीन सीमा',
    'Enable': 'सक्रिय पार्नुहोस्',
    'Enable Emergency Alerts': 'आपतकालीन सूचना सक्रिय गर्नुहोस्',
    'Enable account': 'खाता सक्रिय पार्नुहोस्',
    'Enable emergency alert sound': 'आपतकालीन सूचनाको ध्वनि सक्रिय गर्नुहोस्',
    'Enabled': 'सक्रिय',
    'Event': 'घटना',
    'Every alert is saved in your X-MAN notifications.': 'हरेक सूचना तपाईंको X-MAN सूचनामा सुरक्षित हुन्छ।',
    'Granted': 'अनुमति दिइएको',
    'Has an active account': 'सक्रिय खाता छ',
    'How delivery works': 'सूचना कसरी पुग्छ',
    'In-app': 'एपभित्र',
    'In-app + push': 'एपभित्र + पुश',
    'In-app notifications': 'एपभित्रका सूचना',
    'In-app only': 'एपभित्र मात्र',
    'In-website emergency alert': 'वेबसाइटभित्रको आपतकालीन सूचना',
    'Last activity': 'अन्तिम गतिविधि',
    'Last delivery': 'अन्तिम वितरण',
    'Last login': 'अन्तिम लगइन',
    'Layers': 'तहहरू',
    'Manage': 'व्यवस्थापन',
    'Mobile': 'मोबाइल',
    'Must change password': 'पासवर्ड परिवर्तन गर्नुपर्ने',
    'Mute alarm': 'अलार्म बन्द गर्नुहोस्',
    'Name': 'नाम',
    'Name or category': 'नाम वा वर्ग',
    'Name, username or email': 'नाम, प्रयोगकर्ता नाम वा इमेल',
    'Needs a secure (HTTPS) connection': 'सुरक्षित (HTTPS) जडान चाहिन्छ',
    'Next': 'अर्को',
    'No': 'होइन',
    'No account': 'खाता छैन',
    'No account linked': 'कुनै खाता जोडिएको छैन',
    'No citizens yet.': 'अहिलेसम्म कुनै नागरिक छैनन्।',
    'No district': 'जिल्ला छैन',
    'No push subscriptions.': 'कुनै पुश सदस्यता छैन।',
    'Not Now': 'अहिले होइन',
    'Not active on this device': 'यो उपकरणमा सक्रिय छैन',
    'Not configured': 'कन्फिगर गरिएको छैन',
    'Not configured: set VAPID_PUBLIC_KEY and VAPID_PRIVATE_KEY': 'कन्फिगर गरिएको छैन: VAPID_PUBLIC_KEY र VAPID_PRIVATE_KEY सेट गर्नुहोस्',
    'Not implemented': 'लागू गरिएको छैन',
    'Not requested': 'अनुरोध गरिएको छैन',
    'Not shared': 'साझा गरिएको छैन',
    'Not supported by this browser': 'यो ब्राउजरले समर्थन गर्दैन',
    'Notification delivery': 'सूचना वितरण',
    'Notification history': 'सूचना इतिहास',
    'Notification permission': 'सूचना अनुमति',
    'Notification status': 'सूचनाको स्थिति',
    'Notifications are blocked for this site. Allow them in your browser settings to receive alerts outside X-MAN.': 'यो साइटका सूचना रोकिएका छन्। X-MAN बाहिर सूचना पाउन ब्राउजर सेटिङमा अनुमति दिनुहोस्।',
    'Notifications received': 'प्राप्त सूचना',
    'OFF': 'बन्द',
    'ON': 'चालु',
    'Off: alerts appear only inside X-MAN.': 'बन्द: सूचना X-MAN भित्र मात्र देखिन्छन्।',
    'Office details': 'कार्यालय विवरण',
    'On: alerts can reach this account even when the website is closed.': 'चालु: वेबसाइट बन्द हुँदा पनि सूचना यो खातामा पुग्न सक्छन्।',
    'Page': 'पृष्ठ',
    'Pagination': 'पृष्ठहरू',
    'Passwords are stored only as one-way hashes and cannot be viewed. A reset sets a temporary password that the authority must change at next login.': 'पासवर्ड एकतर्फी ह्यासका रूपमा मात्र राखिन्छन् र हेर्न सकिँदैन। रिसेटले अस्थायी पासवर्ड राख्छ, जुन निकायले अर्को लगइनमा परिवर्तन गर्नुपर्छ।',
    'Play alarm': 'अलार्म बजाउनुहोस्',
    'Preview sound': 'ध्वनि सुन्नुहोस्',
    'Previous': 'अघिल्लो',
    'Push off': 'पुश बन्द',
    'Push on': 'पुश चालु',
    'Push subscription': 'पुश सदस्यता',
    'Push-enabled users': 'पुश सक्रिय प्रयोगकर्ता',
    'Recent emergency events': 'हालका आपतकालीन घटना',
    'Recent hazard notifications': 'हालका जोखिम सूचना',
    'Recipients': 'प्राप्तकर्ता',
    'Registered': 'दर्ता मिति',
    'Reset password': 'पासवर्ड रिसेट',
    'SMS': 'एसएमएस',
    'SMS alerts are not available yet.': 'एसएमएस सूचना अहिले उपलब्ध छैन।',
    'Search': 'खोज्नुहोस्',
    'Sent': 'पठाइएको',
    'Set temporary password': 'अस्थायी पासवर्ड राख्नुहोस्',
    'Settings come from the server environment and are read-only here. The VAPID private key is never shown.': 'सेटिङ सर्भरको वातावरणबाट आउँछन् र यहाँ हेर्न मात्र मिल्छ। VAPID निजी कुञ्जी कहिल्यै देखाइँदैन।',
    'Severity': 'गम्भीरता',
    'Shared by the citizen': 'नागरिकले साझा गरेको',
    'Temporary password': 'अस्थायी पासवर्ड',
    'Test Emergency Notification': 'आपतकालीन सूचना परीक्षण',
    'Test notification could not be sent.': 'परीक्षण सूचना पठाउन सकिएन।',
    'Test notification sent. It may take a few seconds to appear.': 'परीक्षण सूचना पठाइयो। देखिन केही सेकेन्ड लाग्न सक्छ।',
    'Time': 'समय',
    'Turn Off Emergency Alerts': 'आपतकालीन सूचना बन्द गर्नुहोस्',
    'Turned off by you.': 'तपाईंले बन्द गर्नुभएको।',
    'Turning off emergency alerts stops optional browser push/sound alerts. X-MAN notification records remain available in your account.': 'आपतकालीन सूचना बन्द गर्दा ऐच्छिक ब्राउजर पुश/ध्वनि सूचना रोकिन्छ। X-MAN सूचनाका अभिलेख तपाईंको खातामा उपलब्ध रहन्छन्।',
    'Users with sound off': 'ध्वनि बन्द गरेका प्रयोगकर्ता',
    'VAPID contact': 'VAPID सम्पर्क',
    'Verified office': 'प्रमाणित कार्यालय',
    'View hazard': 'जोखिम हेर्नुहोस्',
    'Web Push': 'वेब पुश',
    'Web emergency alerts (outside the website)': 'वेब आपतकालीन सूचना (वेबसाइट बाहिर)',
    'While X-MAN is open, emergencies appear as an on-screen alert with optional sound.': 'X-MAN खुला हुँदा आपतकालीन अवस्था स्क्रिनमा सूचनाका रूपमा ऐच्छिक ध्वनिसहित देखिन्छ।',
    'With emergency alerts enabled, your browser can show them even when X-MAN is closed.': 'आपतकालीन सूचना सक्रिय भए X-MAN बन्द हुँदा पनि तपाईंको ब्राउजरले देखाउन सक्छ।',
    'X-MAN can deliver browser push emergency notifications outside the website when your browser/device supports Web Push, permission is granted, and the device has network connectivity. Your browser and operating system control whether notifications are shown and whether they make a sound.': 'तपाईंको ब्राउजर/उपकरणले वेब पुश समर्थन गरे, अनुमति दिइए र उपकरणमा इन्टरनेट जडान भए X-MAN ले वेबसाइट बाहिर ब्राउजर पुश आपतकालीन सूचना पठाउन सक्छ। सूचना देखिने वा ध्वनि बज्ने कुरा तपाईंको ब्राउजर र अपरेटिङ सिस्टमले नियन्त्रण गर्छ।',
    'X-MAN can send emergency disaster alerts even when this website is closed. You can disable this anytime from notification settings.': 'यो वेबसाइट बन्द हुँदा पनि X-MAN ले आपतकालीन विपद् सूचना पठाउन सक्छ। सूचना सेटिङबाट जुनसुकै बेला बन्द गर्न सक्नुहुन्छ।',
    'Yes': 'हो',
    'Your browser blocked the alarm sound until you interact with the page.': 'तपाईंले पृष्ठमा केही नथिचेसम्म ब्राउजरले अलार्म ध्वनि रोकेको छ।',
    'active subscriptions': 'सक्रिय सदस्यता',
    'and above': 'र माथि',
    'authorities': 'निकायहरू',
    'authority accounts': 'निकायका खाता',
    'citizens': 'नागरिक',
    'citizens / push enabled': 'नागरिक / पुश सक्रिय',
    'coordinates are not shown in the admin panel': 'प्रशासन प्यानलमा निर्देशाङ्क देखाइँदैन',
    'disabled accounts': 'निष्क्रिय खाता',
    'expired or repeatedly failing': 'म्याद सकिएका वा बारम्बार असफल',
    'more active emergency alerts': 'थप सक्रिय आपतकालीन सूचना',
    'push': 'पुश',
    'push enabled': 'पुश सक्रिय',
    'temporary': 'अस्थायी',
    'website alert': 'वेबसाइट सूचना',
    'with recent failures': 'हालै असफल भएका',
    'This account has been disabled. Contact an administrator.': 'यो खाता निष्क्रिय पारिएको छ। प्रशासकलाई सम्पर्क गर्नुहोस्।',
    'Password must be at least 8 characters.': 'पासवर्ड कम्तीमा ८ अक्षरको हुनुपर्छ।',
    'Choose a password different from the current one.': 'हालको भन्दा फरक पासवर्ड छान्नुहोस्।',
}

PAGE_TEXT = {'ne': NE}


def page_translation(lang, text):
    """Translate one page string. Unknown strings and English fall through."""
    if not text:
        return text
    lang = FALLBACK.get(lang, lang)
    return PAGE_TEXT.get(lang, {}).get(text, text)
