# -*- coding: utf-8 -*-
"""Page-content translations, keyed by the exact English string in the template.

Templates call these through the `|t` Jinja filter: `{{ 'Road Status'|t }}`.
English is the source language, so there is no 'en' dict — a lookup for 'en'
returns the key itself.

ponytail: Newari and Maithili fall back to Nepali for page content (see
FALLBACK). The short UI keys in translation_service.py are properly translated
into all four; hand-translating 350 page strings into Newari and Maithili needs
a speaker of each, and inventing them would be worse than falling back.
"""

FALLBACK = {'newari': 'ne', 'maithili': 'ne'}

NE = {
    # --- auth ---
    'Authority Login': 'निकाय लगइन',
    'Government & Organization Access': 'सरकारी तथा संस्थागत पहुँच',
    'Username': 'प्रयोगकर्ता नाम',
    'Password': 'पासवर्ड',
    'Remember me': 'मलाई सम्झनुहोस्',
    'Login to Authority Panel': 'निकाय प्यानलमा लगइन गर्नुहोस्',
    'Register as Authority': 'निकायको रूपमा दर्ता गर्नुहोस्',
    'Citizen Login': 'नागरिक लगइन',
    'Enter authority username': 'निकायको प्रयोगकर्ता नाम लेख्नुहोस्',
    'Enter password': 'पासवर्ड लेख्नुहोस्',
    'Authority Registration': 'निकाय दर्ता',
    'Register your government organization': 'आफ्नो सरकारी संस्था दर्ता गर्नुहोस्',
    'Organization Name': 'संस्थाको नाम',
    'Organization email': 'संस्थाको इमेल',
    'Choose username': 'प्रयोगकर्ता नाम छान्नुहोस्',
    'Create password': 'पासवर्ड बनाउनुहोस्',
    'Register Authority Account': 'निकाय खाता दर्ता गर्नुहोस्',
    'Citizen Registration': 'नागरिक दर्ता',
    'e.g., Sindhuli Road Division Office': 'जस्तै, सिन्धुली सडक डिभिजन कार्यालय',
    'Welcome Back': 'पुनः स्वागत छ',
    'Login to continue to your dashboard': 'आफ्नो ड्यासबोर्डमा जान लगइन गर्नुहोस्',
    'Login': 'लगइन',
    "Don't have an account?": 'खाता छैन?',
    'Register here': 'यहाँ दर्ता गर्नुहोस्',
    'Enter your username': 'आफ्नो प्रयोगकर्ता नाम लेख्नुहोस्',
    'Enter your password': 'आफ्नो पासवर्ड लेख्नुहोस्',
    'Create Account': 'खाता खोल्नुहोस्',
    'Join your district on NepalSathi': 'नेपालसाथीमा आफ्नो जिल्लासँग जोडिनुहोस्',
    'Register': 'दर्ता',
    'Already have an account?': 'पहिले नै खाता छ?',
    'Login here': 'यहाँ लगइन गर्नुहोस्',
    'Choose a username': 'प्रयोगकर्ता नाम छान्नुहोस्',
    'Enter your email': 'आफ्नो इमेल लेख्नुहोस्',
    'Create a password': 'पासवर्ड बनाउनुहोस्',

    # --- shared labels ---
    'Category': 'श्रेणी',
    'District': 'जिल्ला',
    'Phone': 'फोन',
    'Email': 'इमेल',
    'Status': 'अवस्था',
    'Description': 'विवरण',
    'Location': 'स्थान',
    'Authority': 'निकाय',
    'Authorities': 'निकायहरू',
    'Province': 'प्रदेश',
    'Districts': 'जिल्लाहरू',
    'Dashboard': 'ड्यासबोर्ड',
    'Projects': 'आयोजनाहरू',
    'Roads': 'सडकहरू',
    'Rivers': 'नदीहरू',
    'Posts': 'पोस्टहरू',
    'Complaints': 'उजुरीहरू',
    'Logout': 'लगआउट',
    'Filter': 'फिल्टर',
    'All Districts': 'सबै जिल्लाहरू',
    'Filter by District:': 'जिल्ला अनुसार छान्नुहोस्:',
    'View All': 'सबै हेर्नुहोस्',
    'View Details': 'विवरण हेर्नुहोस्',
    'Category:': 'श्रेणी:',
    'Urgency:': 'अत्यावश्यकता:',
    'Location:': 'स्थान:',
    'Status:': 'अवस्था:',
    'Filed by:': 'दर्ता गर्ने:',
    'Filed on:': 'दर्ता मिति:',
    'Filed:': 'दर्ता:',
    'Last Updated:': 'अन्तिम अद्यावधिक:',
    'Description:': 'विवरण:',
    'Progress:': 'प्रगति:',
    'Phone:': 'फोन:',
    'Email:': 'इमेल:',
    'Address:': 'ठेगाना:',
    'Hours:': 'समय:',
    'Ticket:': 'टिकट:',
    'Level:': 'सतह:',
    'Danger:': 'खतरा:',
    'Date:': 'मिति:',
    'Time:': 'समय:',
    'Route:': 'मार्ग:',
    'Distance:': 'दूरी:',
    'Budget:': 'बजेट:',
    'Spent:': 'खर्च:',
    'Contractor:': 'निर्माण कम्पनी:',
    'Start Date:': 'सुरु मिति:',
    'Expected Completion:': 'सम्भावित सम्पन्न मिति:',
    'Current Level:': 'हालको सतह:',
    'Danger Level:': 'खतरा सतह:',
    'Your District:': 'तपाईंको जिल्ला:',
    'Joined:': 'सामेल मिति:',
    'Headquarters:': 'सदरमुकाम:',
    'District ID:': 'जिल्ला आईडी:',
    'Authority ID:': 'निकाय आईडी:',
    'Response:': 'जवाफ:',
    'VERIFIED': 'प्रमाणित',
    'VERIFIED AUTHORITY': 'प्रमाणित निकाय',
    'CITIZEN': 'नागरिक',
    'km': 'कि.मि.',
    'complete': 'सम्पन्न',
    'posts': 'पोस्टहरू',
    'complaints': 'उजुरीहरू',
    'Not specified': 'उल्लेख गरिएको छैन',
    'N/A': 'उपलब्ध छैन',

    # --- categories and statuses (also rendered raw from the database) ---
    'Road Division': 'सडक डिभिजन',
    'Police': 'प्रहरी',
    'Electricity Authority': 'विद्युत प्राधिकरण',
    'Electricity': 'विद्युत',
    'Water Supply': 'खानेपानी',
    'Health Office': 'स्वास्थ्य कार्यालय',
    'Municipality': 'नगरपालिका',
    'Disaster Management': 'विपद् व्यवस्थापन',
    'Other': 'अन्य',
    'Road Blocked': 'सडक अवरुद्ध',
    'Waste Management': 'फोहोर व्यवस्थापन',
    'Landslide': 'पहिरो',
    'Bridge Damage': 'पुल क्षति',
    'Drainage': 'ढल',
    'Pending': 'विचाराधीन',
    'In Progress': 'कार्यरत',
    'Resolved': 'समाधान भयो',
    'Rejected': 'अस्वीकृत',
    'Normal': 'सामान्य',
    'Rising': 'बढ्दै',
    'High': 'उच्च',
    'Medium': 'मध्यम',
    'Low': 'कम',
    'Critical': 'अति जरुरी',
    'Flooding': 'बाढी',
    'Flood': 'बाढी',
    'Open': 'खुला',
    'Partially Open': 'आंशिक खुला',
    'Restricted': 'प्रतिबन्धित',
    'Blocked': 'अवरुद्ध',
    'Moderate': 'मध्यम',
    'Heavy': 'धेरै',
    'Severe': 'अति धेरै',
    'Traffic': 'ट्राफिक',
    'Road Condition': 'सडक अवस्था',
    'Weather': 'मौसम',
    'Development': 'विकास',
    'News': 'समाचार',
    'Emergency': 'आपतकालीन',
    'road': 'सडक',
    'police': 'प्रहरी',
    'electricity': 'विद्युत',
    'water': 'खानेपानी',
    'water_supply': 'खानेपानी',
    'health': 'स्वास्थ्य',
    'municipality': 'नगरपालिका',
    'disaster': 'विपद्',
    'other': 'अन्य',
    'open': 'खुला',
    'partial': 'आंशिक',
    'restricted': 'प्रतिबन्धित',
    'blocked': 'अवरुद्ध',
    'low': 'कम',
    'moderate': 'मध्यम',
    'heavy': 'धेरै',
    'severe': 'अति धेरै',
    'normal': 'सामान्य',
    'rising': 'बढ्दै',
    'high': 'उच्च',
    'medium': 'मध्यम',
    'critical': 'अति जरुरी',
    'flooding': 'बाढी',
    'flood': 'बाढी',
    'pending': 'विचाराधीन',
    'in_progress': 'कार्यरत',
    'resolved': 'समाधान भयो',
    'rejected': 'अस्वीकृत',
    'on_schedule': 'समयमै',
    'delayed': 'ढिलो',
    'completed': 'सम्पन्न',
    'road_blocked': 'सडक अवरुद्ध',
    'waste': 'फोहोर',
    'landslide': 'पहिरो',
    'bridge': 'पुल',
    'drainage': 'ढल',
    'traffic': 'ट्राफिक',
    'road_condition': 'सडक अवस्था',
    'weather': 'मौसम',
    'development': 'विकास',
    'emergency': 'आपतकालीन',
    'news': 'समाचार',
    'general': 'सामान्य',
    'announcement': 'घोषणा',
    'progress': 'प्रगति',

    # --- navigation and chrome ---
    'Select language': 'भाषा छान्नुहोस्',
    'Language': 'भाषा',
    'District Intelligence': 'जिल्ला जानकारी',
    'Overview': 'सिंहावलोकन',
    'Infrastructure': 'पूर्वाधार',
    'Community': 'समुदाय',
    'Civic': 'नागरिक',
    'Dark mode': 'डार्क मोड',
    'Switch to dark mode': 'डार्क मोडमा जानुहोस्',
    'Toggle navigation': 'मेनु खोल्नुहोस् वा बन्द गर्नुहोस्',
    'Main': 'मुख्य',
    'Account': 'खाता',

    # --- authority panel ---
    'Authority Panel': 'निकाय प्यानल',
    'Authority Dashboard': 'निकाय ड्यासबोर्ड',
    'Total Complaints': 'कुल उजुरीहरू',
    'Recent Complaints': 'हालका उजुरीहरू',
    'No complaints.': 'कुनै उजुरी छैन।',
    'No complaints filed.': 'कुनै उजुरी दर्ता भएको छैन।',
    'Manage Projects': 'आयोजना व्यवस्थापन',
    'No projects assigned.': 'कुनै आयोजना तोकिएको छैन।',
    'Manage your development projects': 'आफ्ना विकास आयोजनाहरू व्यवस्थापन गर्नुहोस्',
    'Update Progress (%)': 'प्रगति अद्यावधिक (%)',
    'Update Description': 'अद्यावधिक विवरण',
    'Update Project': 'आयोजना अद्यावधिक गर्नुहोस्',
    'Describe the update...': 'अद्यावधिकको विवरण लेख्नुहोस्...',
    'River Management': 'नदी व्यवस्थापन',
    'Update river levels and issue warnings': 'नदीको सतह अद्यावधिक गरी चेतावनी जारी गर्नुहोस्',
    'Water Level (m)': 'पानीको सतह (मि.)',
    'Update River': 'नदी अद्यावधिक गर्नुहोस्',
    'No rivers in your district.': 'तपाईंको जिल्लामा कुनै नदी छैन।',
    'Road Management': 'सडक व्यवस्थापन',
    'Update road status in your district': 'आफ्नो जिल्लाको सडक अवस्था अद्यावधिक गर्नुहोस्',
    'Traffic Level': 'ट्राफिक स्तर',
    'Update Road': 'सडक अद्यावधिक गर्नुहोस्',
    'No roads in your district.': 'तपाईंको जिल्लामा कुनै सडक छैन।',
    'Complaint Details': 'उजुरी विवरण',
    'Previous Responses': 'अघिल्ला जवाफहरू',
    'No responses yet.': 'अहिलेसम्म कुनै जवाफ छैन।',
    'Send Response': 'जवाफ पठाउनुहोस्',
    'Update Status': 'अवस्था अद्यावधिक गर्नुहोस्',
    'Response Message': 'जवाफ सन्देश',
    'Type your response...': 'आफ्नो जवाफ लेख्नुहोस्...',
    'Respond': 'जवाफ दिनुहोस्',
    'All complaints filed to': 'यहाँ दर्ता भएका सबै उजुरीहरू:',

    # --- ai assistant ---
    'NepalSathi AI Assistant': 'नेपालसाथी एआई सहायक',
    'Ask questions about roads, rivers, projects, and travel in Nepal': 'नेपालका सडक, नदी, आयोजना र यात्राबारे प्रश्न सोध्नुहोस्',
    'Checking AI status...': 'एआई अवस्था जाँच गर्दै...',
    'I can help you with:': 'म तपाईंलाई यसमा सहयोग गर्न सक्छु:',
    'Road conditions in Nepal': 'नेपालको सडक अवस्था',
    'River levels and flood warnings': 'नदीको सतह र बाढी चेतावनी',
    'Development projects': 'विकास आयोजनाहरू',
    'Travel planning': 'यात्रा योजना',
    'Authority information': 'निकायसम्बन्धी जानकारी',
    'Emergency numbers': 'आपतकालीन नम्बरहरू',
    'Flood Warnings': 'बाढी चेतावनी',
    'Travel Advice': 'यात्रा सल्लाह',
    'File Complaint': 'उजुरी दर्ता',
    'Send': 'पठाउनुहोस्',
    'Type your question about Nepal...': 'नेपालबारे आफ्नो प्रश्न लेख्नुहोस्...',
    'Powered by Local AI (Ollama) • Qwen 2.5': 'स्थानीय एआई (Ollama) • Qwen 2.5 द्वारा सञ्चालित',

    # --- authority directory ---
    'Authority Directory': 'निकाय निर्देशिका',
    'Government authorities in your district': 'तपाईंको जिल्लाका सरकारी निकायहरू',

    # --- password and profile ---
    'Change Password': 'पासवर्ड परिवर्तन',
    'Current Password': 'हालको पासवर्ड',
    'New Password': 'नयाँ पासवर्ड',
    'Confirm New Password': 'नयाँ पासवर्ड पुष्टि गर्नुहोस्',
    'Back to Edit Profile': 'प्रोफाइल सम्पादनमा फर्कनुहोस्',
    'Edit Profile': 'प्रोफाइल सम्पादन',
    'Update your profile information': 'आफ्नो प्रोफाइल जानकारी अद्यावधिक गर्नुहोस्',
    'Phone (optional)': 'फोन (वैकल्पिक)',
    'Select District': 'जिल्ला छान्नुहोस्',
    'Bio (optional)': 'परिचय (वैकल्पिक)',
    'Save Changes': 'परिवर्तन सुरक्षित गर्नुहोस्',
    'Tell us about yourself...': 'आफ्नोबारे लेख्नुहोस्...',
    'Go to Authority Dashboard': 'निकाय ड्यासबोर्डमा जानुहोस्',
    'Reputation': 'प्रतिष्ठा',
    'Showing 10 of': 'देखाइएको: १० मध्ये',
    'Showing 5 of': 'देखाइएको: ५ मध्ये',
    'Create your first post': 'आफ्नो पहिलो पोस्ट सिर्जना गर्नुहोस्',
    'File a complaint': 'उजुरी दर्ता गर्नुहोस्',

    # --- complaints (citizen) ---
    'Government Response': 'सरकारी जवाफ',
    'Resolution Details': 'समाधान विवरण',
    'Back to My Complaints': 'मेरा उजुरीहरूमा फर्कनुहोस्',
    'My Complaints': 'मेरा उजुरीहरू',
    'Track your filed complaints': 'आफूले दर्ता गरेका उजुरीहरू ट्र्याक गर्नुहोस्',
    'No complaints filed yet.': 'अहिलेसम्म कुनै उजुरी दर्ता भएको छैन।',
    'File Your First Complaint': 'आफ्नो पहिलो उजुरी दर्ता गर्नुहोस्',
    'File a Complaint': 'उजुरी दर्ता गर्नुहोस्',
    'Report issues to the right authority': 'सही निकायमा समस्या जाहेर गर्नुहोस्',
    'Urgency': 'अत्यावश्यकता',
    'Submit Complaint': 'उजुरी पेश गर्नुहोस्',
    'Describe the issue...': 'समस्याको विवरण लेख्नुहोस्...',
    'e.g., Kamalamai, Sindhuli': 'जस्तै, कमलामाई, सिन्धुली',
    'Complaint': 'उजुरी',

    # --- posts and feed ---
    'Create Post': 'पोस्ट सिर्जना',
    '+ Create Post': '+ पोस्ट सिर्जना',
    'Share information with your community. AI will auto-classify your post.': 'आफ्नो समुदायसँग जानकारी साझा गर्नुहोस्। एआईले तपाईंको पोस्ट स्वतः वर्गीकरण गर्नेछ।',
    'Location (optional)': 'स्थान (वैकल्पिक)',
    'Content': 'सामग्री',
    'Add Photo (optional)': 'फोटो थप्नुहोस् (वैकल्पिक)',
    'Supported: PNG, JPG, JPEG, GIF, WEBP (Max 16MB)': 'समर्थित: PNG, JPG, JPEG, GIF, WEBP (अधिकतम 16MB)',
    'AI Will Classify This As:': 'एआईले यसलाई यसरी वर्गीकरण गर्नेछ:',
    'Post': 'पोस्ट',
    "What's happening? (Nepali or English)": 'के भइरहेको छ? (नेपाली वा अंग्रेजी)',
    'Preview': 'पूर्वावलोकन',
    'Community Feed': 'सामुदायिक फिड',
    'Latest updates from your community': 'तपाईंको समुदायका पछिल्ला अपडेटहरू',
    'Posts tagged with #': '# सँग ट्याग गरिएका पोस्टहरू',
    'Posts from selected district': 'छानिएको जिल्लाका पोस्टहरू',
    'All Categories': 'सबै श्रेणीहरू',
    'Trending Topics': 'चर्चित विषयहरू',
    'Photo': 'फोटो',
    'Post photo': 'पोस्टको फोटो',
    'Like': 'मन पर्‍यो',
    'Comment': 'टिप्पणी',
    'Comments': 'टिप्पणीहरू',
    'Share': 'साझा गर्नुहोस्',
    'The feed is showing your district. Be the first to share something here, or browse posts from across Nepal.': 'फिडले तपाईंको जिल्ला देखाइरहेको छ। यहाँ सबैभन्दा पहिले केही साझा गर्नुहोस्, वा नेपालभरका पोस्टहरू हेर्नुहोस्।',
    'View all districts': 'सबै जिल्लाहरू हेर्नुहोस्',
    'No posts found': 'कुनै पोस्ट भेटिएन',
    'Be the first to share something!': 'सबैभन्दा पहिले केही साझा गर्नुहोस्!',
    'No posts in': 'यहाँ कुनै पोस्ट छैन:',
    'yet': 'अहिलेसम्म',
    'Click to view full size': 'पूरा आकारमा हेर्न क्लिक गर्नुहोस्',
    'AI Classified': 'एआईद्वारा वर्गीकृत',
    'Classified by AI': 'एआईद्वारा वर्गीकृत',
    'Has Photo': 'फोटो सहित',
    'No comments yet. Be the first to comment!': 'अहिलेसम्म कुनै टिप्पणी छैन। सबैभन्दा पहिले टिप्पणी गर्नुहोस्!',
    'Add Comment': 'टिप्पणी थप्नुहोस्',
    'Back to Feed': 'फिडमा फर्कनुहोस्',
    'Write a comment...': 'टिप्पणी लेख्नुहोस्...',
    'Nepali': 'नेपाली',
    'English': 'अंग्रेजी',

    # --- citizen dashboard ---
    'Welcome,': 'स्वागत छ,',
    'Select your district': 'आफ्नो जिल्ला छान्नुहोस्',
    'Road Segments': 'सडक खण्डहरू',
    'Recent Posts': 'हालका पोस्टहरू',
    'Nationwide': 'राष्ट्रव्यापी',
    'Road Status': 'सडक अवस्था',
    'River Status': 'नदी अवस्था',
    'Development Projects': 'विकास आयोजनाहरू',
    'View All Roads': 'सबै सडक हेर्नुहोस्',
    'View All Rivers': 'सबै नदी हेर्नुहोस्',
    'View All Projects': 'सबै आयोजना हेर्नुहोस्',
    'No road data available.': 'सडक डाटा उपलब्ध छैन।',
    'No river data available.': 'नदी डाटा उपलब्ध छैन।',
    'No projects available.': 'कुनै आयोजना उपलब्ध छैन।',
    'View Post': 'पोस्ट हेर्नुहोस्',
    'No posts yet.': 'अहिलेसम्म कुनै पोस्ट छैन।',
    'Create First Post': 'पहिलो पोस्ट सिर्जना गर्नुहोस्',

    # --- districts ---
    "Nepal's 77 Districts": 'नेपालका ७७ जिल्लाहरू',
    'Select your district to see local information': 'स्थानीय जानकारी हेर्न आफ्नो जिल्ला छान्नुहोस्',

    # --- projects ---
    'Development Project Tracker': 'विकास आयोजना ट्र्याकर',
    'Track development projects across Nepal': 'नेपालभरका विकास आयोजनाहरू ट्र्याक गर्नुहोस्',
    'Project Details': 'आयोजना विवरण',
    'Progress Updates': 'प्रगति अपडेटहरू',
    'No updates yet.': 'अहिलेसम्म कुनै अपडेट छैन।',
    'Total Budget': 'कुल बजेट',
    'Spent': 'खर्च',
    'Complete': 'सम्पन्न',

    # --- roads and rivers ---
    'Live Road Status': 'प्रत्यक्ष सडक अवस्था',
    'Real-time road conditions across Nepal': 'नेपालभरको वास्तविक समयको सडक अवस्था',
    'Monitor river levels and flood risks': 'नदीको सतह र बाढीको जोखिम अनुगमन गर्नुहोस्',
    'of danger level': 'खतरा सतहको',

    # --- travel ---
    'Travel Planner': 'यात्रा योजना',
    'Plan your journey with live road and river information': 'प्रत्यक्ष सडक र नदी जानकारीसहित आफ्नो यात्रा योजना बनाउनुहोस्',
    'Plan Your Journey': 'आफ्नो यात्रा योजना बनाउनुहोस्',
    'From': 'बाट',
    'To': 'सम्म',
    'Travel Date': 'यात्रा मिति',
    'Preferred Time': 'रुचाइएको समय',
    'Flexible': 'लचिलो',
    'Morning (6AM - 10AM)': 'बिहान (६ - १० बजे)',
    'Afternoon (10AM - 4PM)': 'दिउँसो (१० - ४ बजे)',
    'Evening (4PM - 8PM)': 'साँझ (४ - ८ बजे)',
    'Analyze Route': 'मार्ग विश्लेषण गर्नुहोस्',
    'e.g., Sindhuli': 'जस्तै, सिन्धुली',
    'e.g., Kathmandu': 'जस्तै, काठमाडौं',
    'Travel Analysis': 'यात्रा विश्लेषण',
    'Travel Score': 'यात्रा अंक',
    'Risk Score': 'जोखिम अंक',
    'Est. Travel Time': 'अनुमानित यात्रा समय',
    'Active Warnings': 'सक्रिय चेतावनीहरू',
    'Road Conditions': 'सडक अवस्था',
    'River Conditions': 'नदी अवस्था',
    'Plan Another Trip': 'अर्को यात्रा योजना बनाउनुहोस्',

    # --- landing ---
    'Sign in': 'लगइन',
    'Get started': 'सुरु गर्नुहोस्',
    'Live across 77 districts': '७७ वटै जिल्लामा प्रत्यक्ष',
    'Know your district.': 'आफ्नो जिल्ला जान्नुहोस्।',
    'Before you travel.': 'यात्रा गर्नुअघि।',
    'Road closures, river levels, and infrastructure projects for every district in Nepal — reported by the people who live there, verified by the authorities who maintain them.': 'नेपालका हरेक जिल्लाका सडक बन्द, नदीको सतह र पूर्वाधार आयोजनाहरू — त्यहीँ बस्ने मानिसहरूले जानकारी दिने, र सम्बन्धित निकायले प्रमाणित गर्ने।',
    'Create free account': 'निःशुल्क खाता खोल्नुहोस्',
    'Create account': 'खाता खोल्नुहोस्',
    'Districts covered': 'समेटिएका जिल्लाहरू',
    'Provinces': 'प्रदेशहरू',
    'Languages': 'भाषाहरू',
    'Community reporting': 'सामुदायिक रिपोर्टिङ',
    'Everything about your district, in one place': 'आफ्नो जिल्लाको सबै जानकारी, एकै ठाउँमा',
    'Built for people who need to know whether the road is open before they set out.': 'हिँड्नुअघि बाटो खुला छ कि छैन थाहा पाउनुपर्नेहरूका लागि बनाइएको।',
    'Road status': 'सडक अवस्था',
    'Segment-level conditions across highways and feeder roads, with closures and construction flagged as they happen.': 'राजमार्ग र सहायक सडकहरूको खण्डगत अवस्था, बन्द र निर्माण भइरहेकै समयमा जनाइने।',
    'River monitoring': 'नदी अनुगमन',
    'Water levels and flood warnings for the rivers that cut through your district, updated through the monsoon.': 'तपाईंको जिल्ला हुँदै बग्ने नदीहरूको सतह र बाढी चेतावनी, मनसुनभरि अद्यावधिक हुने।',
    'Project tracking': 'आयोजना ट्र्याकिङ',
    'Follow bridges, roads, and public works from budget to completion — with real progress, not press releases.': 'पुल, सडक र सार्वजनिक निर्माणलाई बजेटदेखि सम्पन्न हुँदासम्म हेर्नुहोस् — प्रेस विज्ञप्ति होइन, वास्तविक प्रगतिसहित।',
    'Direct complaints': 'सीधा उजुरी',
    'File an issue against the responsible authority and track its status until somebody answers for it.': 'जिम्मेवार निकायविरुद्ध समस्या दर्ता गर्नुहोस् र जवाफ नआउन्जेल त्यसको अवस्था ट्र्याक गर्नुहोस्।',
    'Check a route end to end before you leave, with a risk score built from current road and river conditions.': 'हिँड्नुअघि पूरा मार्ग जाँच्नुहोस्, हालको सडक र नदी अवस्थाबाट बनेको जोखिम अंकसहित।',
    'AI assistant': 'एआई सहायक',
    'Ask about conditions in plain Nepali or English and get an answer drawn from live district data.': 'सामान्य नेपाली वा अंग्रेजीमा अवस्थाबारे सोध्नुहोस् र प्रत्यक्ष जिल्ला डाटामा आधारित जवाफ पाउनुहोस्।',
    'How it works': 'यसले कसरी काम गर्छ',
    'Three steps from signing up to knowing what is happening on the ground.': 'दर्ता गरेदेखि जमिनमा के भइरहेको छ थाहा पाउनसम्म तीन चरण।',
    'Pick your district': 'आफ्नो जिल्ला छान्नुहोस्',
    'Choose where you live or where you are heading. Everything you see is filtered to that district.': 'आफू बस्ने वा जाने ठाउँ छान्नुहोस्। तपाईंले देख्ने सबै जानकारी त्यही जिल्लाको हुनेछ।',
    'See live conditions': 'प्रत्यक्ष अवस्था हेर्नुहोस्',
    'Roads, rivers, and projects on one dashboard, combining community reports with authority updates.': 'सडक, नदी र आयोजनाहरू एउटै ड्यासबोर्डमा, सामुदायिक रिपोर्ट र निकायका अपडेट सँगै।',
    'Report and follow up': 'जानकारी दिनुहोस् र पछ्याउनुहोस्',
    'Post what you see, file complaints, and track them through to a response.': 'आफूले देखेको पोस्ट गर्नुहोस्, उजुरी दर्ता गर्नुहोस् र जवाफ नआउन्जेल पछ्याउनुहोस्।',
    'Start with your district': 'आफ्नो जिल्लाबाट सुरु गर्नुहोस्',
    'Free to use, in Nepali, Newari, Maithili, and English.': 'निःशुल्क, नेपाली, नेवारी, मैथिली र अंग्रेजीमा उपलब्ध।',
    'District intelligence for Nepal': 'नेपालका लागि जिल्ला जानकारी',
    'NepalSathi — District Intelligence for Nepal': 'नेपालसाथी — नेपालका लागि जिल्ला जानकारी',

    # --- flashed messages ---
    'No authority is linked to your account. Contact an administrator.': 'तपाईंको खातामा कुनै निकाय जोडिएको छैन। प्रशासकलाई सम्पर्क गर्नुहोस्।',
    'Authority account required.': 'निकाय खाता आवश्यक छ।',
    'Invalid username or password.': 'प्रयोगकर्ता नाम वा पासवर्ड मिलेन।',
    'Registration successful! Please login.': 'दर्ता सफल भयो! कृपया लगइन गर्नुहोस्।',
    'Welcome to Authority Panel!': 'निकाय प्यानलमा स्वागत छ!',
    'Authority account created! Please login.': 'निकाय खाता बन्यो! कृपया लगइन गर्नुहोस्।',
    'You have been logged out.': 'तपाईं लगआउट हुनुभयो।',
    'All fields are required.': 'सबै विवरण भर्नु आवश्यक छ।',
    'Username already exists.': 'यो प्रयोगकर्ता नाम पहिले नै छ।',
    'Email already registered.': 'यो इमेल पहिले नै दर्ता भइसकेको छ।',
    'This account is not an authority account.': 'यो खाता निकाय खाता होइन।',
    'Project updated!': 'आयोजना अद्यावधिक भयो!',
    'Road status updated!': 'सडक अवस्था अद्यावधिक भयो!',
    'River status updated!': 'नदी अवस्था अद्यावधिक भयो!',
    'Rs.': 'रु.',
    'Cr': 'करोड',
    'User #': 'प्रयोगकर्ता #',
    'Complaint Detail': 'उजुरी विवरण',
    'Test Posts': 'परीक्षण पोस्टहरू',
    'Crore': 'करोड',
    'AI Assistant': 'एआई सहायक',
    'AI Test': 'एआई परीक्षण',
    'Project Tracker': 'आयोजना ट्र्याकर',
    'unknown': 'अज्ञात',
    'Unknown': 'अज्ञात',
    'closed': 'बन्द',
    'under_construction': 'निर्माणाधीन',
    'planned': 'योजनामा',
    'Authority and description are required.': 'निकाय र विवरण अनिवार्य छ।',
    'Category and description are required.': 'श्रेणी र विवरण अनिवार्य छ।',
    'Comment added!': 'टिप्पणी थपियो!',
    'Current password is incorrect.': 'हालको पासवर्ड मिलेन।',
    'District selected successfully!': 'जिल्ला सफलतापूर्वक छानियो!',
    'Incident reported successfully!': 'घटना सफलतापूर्वक जाहेर गरियो!',
    'New passwords do not match.': 'नयाँ पासवर्डहरू मिलेनन्।',
    'No authority found for your account.': 'तपाईंको खाताको लागि कुनै निकाय भेटिएन।',
    'Password changed successfully!': 'पासवर्ड सफलतापूर्वक परिवर्तन भयो!',
    'Password must be at least 6 characters.': 'पासवर्ड कम्तीमा ६ अक्षरको हुनुपर्छ।',
    'Please enter both locations.': 'कृपया दुवै स्थान लेख्नुहोस्।',
    'Post content is required.': 'पोस्टको सामग्री अनिवार्य छ।',
    'Profile updated successfully!': 'प्रोफाइल सफलतापूर्वक अद्यावधिक भयो!',
    'Project updated successfully!': 'आयोजना सफलतापूर्वक अद्यावधिक भयो!',
    'Response sent successfully!': 'जवाफ सफलतापूर्वक पठाइयो!',
    'River status updated successfully!': 'नदी अवस्था सफलतापूर्वक अद्यावधिक भयो!',
    'Unsupported language': 'यो भाषा समर्थित छैन',
    'Username already taken.': 'यो प्रयोगकर्ता नाम पहिले नै लिइएको छ।',
    # --- notifications (M03) ---
    'Notifications': 'सूचनाहरू',
    'unread': 'नपढिएको',
    'Mark all as read': 'सबै पढिएको चिन्ह लगाउनुहोस्',
    'Mark as read': 'पढिएको चिन्ह लगाउनुहोस्',
    'View': 'हेर्नुहोस्',
    'No notifications yet.': 'अहिलेसम्म कुनै सूचना छैन।',
    'earthquake': 'भूकम्प',
    'road_damage': 'सडक क्षति',
    # --- citizen reports (M05) ---
    'Report a Hazard': 'जोखिम रिपोर्ट गर्नुहोस्',
    'My Reports': 'मेरा रिपोर्टहरू',
    'Send a photo of a landslide or road damage. Authorities will review it.': 'पहिरो वा सडक क्षतिको फोटो पठाउनुहोस्। निकायले यसको समीक्षा गर्नेछ।',
    'What did you see?': 'तपाईंले के देख्नुभयो?',
    'Take a photo or choose one. JPG, PNG or WEBP, up to': 'फोटो खिच्नुहोस् वा छान्नुहोस्। JPG, PNG वा WEBP, अधिकतम',
    'Use My Location': 'मेरो स्थान प्रयोग गर्नुहोस्',
    'Latitude': 'अक्षांश',
    'Longitude': 'देशान्तर',
    'Optional. If location access is blocked, type the coordinates or leave them empty.': 'वैकल्पिक। स्थान पहुँच बन्द भए निर्देशांक लेख्नुहोस् वा खाली छोड्नुहोस्।',
    'Nearby landmark (optional)': 'नजिकको चिनारी स्थान (वैकल्पिक)',
    'e.g., near the bridge at Kamalamai': 'जस्तै, कमलामाईको पुल नजिक',
    'Shown publicly with the hazard.': 'यो जोखिमसँगै सार्वजनिक रूपमा देखिन्छ।',
    'Description (optional)': 'विवरण (वैकल्पिक)',
    'Only you and the reviewing authority can see this.': 'यो तपाईं र समीक्षा गर्ने निकायले मात्र देख्न सक्छन्।',
    'Submit Report': 'रिपोर्ट पठाउनुहोस्',
    'Getting location…': 'स्थान लिँदै…',
    'Location added.': 'स्थान थपियो।',
    'Location unavailable. You can type it or leave it empty.': 'स्थान उपलब्ध भएन। तपाईं लेख्न वा खाली छोड्न सक्नुहुन्छ।',
    'Please add a photo.': 'कृपया फोटो थप्नुहोस्।',
    'Sending…': 'पठाउँदै…',
    'Could not send the report. Please try again.': 'रिपोर्ट पठाउन सकिएन। फेरि प्रयास गर्नुहोस्।',
    'Report sent. Thank you — authorities will review it.': 'रिपोर्ट पठाइयो। धन्यवाद — निकायले समीक्षा गर्नेछ।',
    'Report photo': 'रिपोर्टको फोटो',
    'Hazard': 'जोखिम',
    'You have not sent any reports yet.': 'तपाईंले अहिलेसम्म कुनै रिपोर्ट पठाउनुभएको छैन।',
    'submitted': 'पेश गरियो',
    'accepted': 'स्वीकृत',
    'detected': 'पत्ता लाग्यो',
    'investigating': 'अनुसन्धान हुँदै',
    'confirmed': 'पुष्टि भयो',
    # --- photo report review (M06) ---
    'Review Photo Reports': 'फोटो रिपोर्ट समीक्षा',
    'AI analysis is evidence only. It never accepts a report or changes a hazard. You decide.': 'एआई विश्लेषण प्रमाण मात्र हो। यसले रिपोर्ट स्वीकार गर्दैन वा जोखिम परिवर्तन गर्दैन। निर्णय तपाईंको हो।',
    'Citizen report': 'नागरिकको रिपोर्ट',
    'AI analysis': 'एआई विश्लेषण',
    'differs from citizen': 'नागरिकको भन्दा फरक',
    'Model confidence': 'मोडेलको विश्वास अंक',
    'Analysis failed. Review the photo manually.': 'विश्लेषण असफल भयो। फोटो आफैं समीक्षा गर्नुहोस्।',
    'Not analyzed': 'विश्लेषण गरिएको छैन',
    'Hazard event': 'जोखिम घटना',
    'Accept': 'स्वीकार गर्नुहोस्',
    'Reject': 'अस्वीकार गर्नुहोस्',
    'Run analysis again': 'फेरि विश्लेषण गर्नुहोस्',
    'No photo reports to review.': 'समीक्षा गर्न कुनै फोटो रिपोर्ट छैन।',
    # --- disaster monitoring dashboard (M07) ---
    'Disaster Monitoring': 'विपद् अनुगमन',
    'Road damage': 'सडक क्षति',
    # --- authority response (M09) ---
    'response': 'प्रतिकार्य जारी',
    'Investigating': 'अनुसन्धान हुँदै',
    'Confirmed': 'पुष्टि भयो',
    'Response in progress': 'प्रतिकार्य जारी',
    'Open response': 'प्रतिकार्य खोल्नुहोस्',
    'notes': 'टिप्पणी',
    'open actions': 'खुला कार्य',
    'Hazard response': 'जोखिम प्रतिकार्य',
    'Lifecycle': 'जीवनचक्र',
    'Note': 'टिप्पणी',
    'required to resolve or reject': 'समाधान वा अस्वीकार गर्न आवश्यक',
    'Start Investigation': 'अनुसन्धान सुरु गर्नुहोस्',
    'Confirm Hazard': 'जोखिम पुष्टि गर्नुहोस्',
    'Start Response': 'प्रतिकार्य सुरु गर्नुहोस्',
    'Resolve Incident': 'घटना समाधान गर्नुहोस्',
    'Reject Hazard': 'जोखिम अस्वीकार गर्नुहोस्',
    'This incident is closed. Resolved and rejected incidents cannot be reopened.': 'यो घटना बन्द छ। समाधान वा अस्वीकृत घटनाहरू फेरि खोल्न मिल्दैन।',
    'Timeline': 'समयरेखा',
    'Hazard detected': 'जोखिम पत्ता लाग्यो',
    'Investigation note': 'अनुसन्धान टिप्पणी',
    'Response action': 'प्रतिकार्य',
    'Add investigation note': 'अनुसन्धान टिप्पणी थप्नुहोस्',
    'Add note': 'टिप्पणी थप्नुहोस्',
    'Response actions': 'प्रतिकार्यहरू',
    'Completed': 'सम्पन्न',
    'No response actions yet.': 'अहिलेसम्म कुनै प्रतिकार्य छैन।',
    'Add response action': 'प्रतिकार्य थप्नुहोस्',
    'What is being done?': 'के गरिँदैछ?',
    'Add action': 'कार्य थप्नुहोस्',
    'Risk assessment (M08 evidence)': 'जोखिम मूल्याङ्कन (M08 प्रमाण)',
    'Sources': 'स्रोतहरू',
    'Evidence only: the assessment never confirms or resolves a hazard.': 'प्रमाण मात्र: मूल्याङ्कनले जोखिम पुष्टि वा समाधान गर्दैन।',
    'A note is required to resolve or reject.': 'समाधान वा अस्वीकार गर्न टिप्पणी आवश्यक छ।',
    'All districts': 'सबै जिल्ला',
    'Refresh': 'ताजा गर्नुहोस्',
    'Active hazards': 'सक्रिय जोखिमहरू',
    'Map': 'नक्सा',
    'Map of active hazards': 'सक्रिय जोखिमहरूको नक्सा',
    'Hazard list': 'जोखिम सूची',
    'IoT devices': 'आईओटी उपकरणहरू',
    'Sensor readings are telemetry only. A vibration or tilt value is not an earthquake detection.': 'सेन्सर रिडिङ टेलिमेट्री मात्र हो। कम्पन वा झुकावको मानले भूकम्प पत्ता लागेको जनाउँदैन।',
    'Citizen photo reports': 'नागरिक फोटो रिपोर्टहरू',
    'AI analysis is evidence only. It never confirms a hazard or changes its severity.': 'एआई विश्लेषण प्रमाण मात्र हो। यसले जोखिम पुष्टि गर्दैन वा गम्भीरता परिवर्तन गर्दैन।',
    'My alerts': 'मेरा सूचनाहरू',
    'System statistics': 'प्रणाली तथ्याङ्क',
    'Earthquake / abnormal ground motion': 'भूकम्प / असामान्य भू-कम्पन',
    'Online': 'अनलाइन',
    'Stale': 'पुरानो डेटा',
    'Offline': 'अफलाइन',
    'Never reported': 'कहिल्यै रिपोर्ट गरेन',
    'Water level': 'पानीको सतह',
    'Temperature': 'तापक्रम',
    'Humidity': 'आर्द्रता',
    'Vibration': 'कम्पन',
    'Tilt': 'झुकाव',
    'Rainfall': 'वर्षा',
    'No active hazards.': 'कुनै सक्रिय जोखिम छैन।',
    'No devices visible to you.': 'तपाईंले हेर्न मिल्ने कुनै उपकरण छैन।',
    'No photo reports.': 'कुनै फोटो रिपोर्ट छैन।',
    'No readings yet': 'अहिलेसम्म रिडिङ छैन',
    'Affected': 'प्रभावित',
    'Source': 'स्रोत',
    'Detected': 'पत्ता लागेको',
    'Updated': 'अद्यावधिक',
    'Last seen': 'अन्तिम पटक देखिएको',
    'ago': 'अघि',
    'min': 'मिनेट',
    'Disabled': 'निष्क्रिय',
    'AI': 'एआई',
    'Analysis failed': 'विश्लेषण असफल',
    'Not on the map (no coordinates):': 'नक्सामा छैन (निर्देशांक छैन):',
    'refreshes every': 'प्रत्येक पटक ताजा हुन्छ:',
    'paused while tab is hidden': 'ट्याब लुकेको बेला रोकिएको छ',
    'Could not load dashboard data.': 'ड्यासबोर्ड डेटा लोड गर्न सकिएन।',
    'Your account is not linked to an authority district.': 'तपाईंको खाता कुनै निकायको जिल्लासँग जोडिएको छैन।',
    'Online = reported within': 'अनलाइन = यति समयभित्र रिपोर्ट गरेको:',
    'stale = within': 'पुरानो = यति समयभित्र:',
    'Events': 'घटनाहरू',
    'Reports': 'रिपोर्टहरू',
    'Notifications (24 h)': 'सूचनाहरू (२४ घण्टा)',
    'Devices': 'उपकरणहरू',
    'Total': 'जम्मा',
    'IoT': 'आईओटी',
    'System': 'प्रणाली',
}

PAGE_TEXT = {'ne': NE}


def page_translation(lang, text):
    """Translate one page string. Unknown strings and English fall through."""
    if not text:
        return text
    lang = FALLBACK.get(lang, lang)
    return PAGE_TEXT.get(lang, {}).get(text, text)
