"""add active_incident_id to seismic_event_states

Revision ID: 48113acd26da
Revises: 6e2814ab4a6e
Create Date: 2026-10-05 10:48:39.260978

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48113acd26da'
down_revision = '6e2814ab4a6e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('seismic_event_states', schema=None) as batch_op:
        batch_op.add_column(sa.Column('active_incident_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_seismic_event_states_active_incident_id'), ['active_incident_id'], unique=False)
        batch_op.create_foreign_key('fk_seismic_event_states_active_incident_id_incidents', 'incidents', ['active_incident_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('seismic_event_states', schema=None) as batch_op:
        batch_op.drop_constraint('fk_seismic_event_states_active_incident_id_incidents', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_seismic_event_states_active_incident_id'))
        batch_op.drop_column('active_incident_id')

    # ### end Alembic commands ###
