"""add seismic_event_states table

Revision ID: 6e2814ab4a6e
Revises: e7413efdd252
Create Date: 2026-10-05 09:33:08.728788

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e2814ab4a6e'
down_revision = 'e7413efdd252'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('seismic_event_states',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.Column('state', sa.String(length=20), nullable=False),
    sa.Column('event_started_at', sa.DateTime(), nullable=True),
    sa.Column('event_ended_at', sa.DateTime(), nullable=True),
    sa.Column('peak_vibration_mg', sa.Float(), nullable=True),
    sa.Column('last_observation_at', sa.DateTime(), nullable=True),
    sa.Column('last_observation_level', sa.String(length=20), nullable=True),
    sa.Column('recovery_window_count', sa.Integer(), nullable=False),
    sa.Column('recovery_started_at', sa.DateTime(), nullable=True),
    sa.Column('recovery_confirmed_at', sa.DateTime(), nullable=True),
    sa.Column('gap_entered_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['iot_devices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('seismic_event_states', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_seismic_event_states_device_id'), ['device_id'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('seismic_event_states', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_seismic_event_states_device_id'))

    op.drop_table('seismic_event_states')
    # ### end Alembic commands ###
